<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved.
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 11:48:21 +0000
// --------------------------------------------------------------------------------

$l['nav_announcements'] = 'Forum Aankondiging';
$l['announcements'] = 'Aankondiging';
$l['forum_announcement'] = 'Forum Aankondiging: {1}';
$l['error_invalidannouncement'] = 'De opgegeven aankondiging is ongeldig.';
$l['announcement_edit'] = 'Aankondiging bewerken';
$l['announcement_qdelete'] = 'Aankondiging verwijderen';
$l['announcement_quickdelete_confirm'] = 'Weet u zeker dat u deze aankondiging wilt verwijderen?';
