<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Fonta
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 02 Jun 2017 08:19:10 +0000
// --------------------------------------------------------------------------------

$l['archive_fullversion'] = 'Volledige versie:';
$l['archive_replies'] = 'Reacties';
$l['archive_reply'] = 'Reactie';
$l['archive_pages'] = 'Pagina\'s:';
$l['archive_note'] = 'U bekijkt momenteel een uitgeklede versie van ons materiaal. <a href="{1}">De volledige versie met bijbehorende opmaak weergeven</a>.';
$l['archive_nopermission'] = 'U heeft geen toegang tot dit onderdeel.';
$l['error_nothreads'] = 'Er zijn momenteel geen topics aanwezig in dit forum.';
$l['error_unapproved_thread'] = 'Dit topic is niet goedgekeurd. Bekijk <a href="{1}">de volledige versie</a> om de inhoud van dit topic te bekijken.';
$l['archive_not_found'] = '<h1>Foutmelding 404: Pagina niet gevonden</h1><p>Het opgegeven document kon niet worden gevonden op deze server.</p>';
$l['error_mustlogin'] = 'Dit forum vereist alle gebruikers om in te loggen.';
$l['error_nopermission'] = 'U heeft geen rechten op topics in dit forum te bekijken.';
