<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Fonta
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Tue, 02 Feb 2016 00:47:09 +0000
// --------------------------------------------------------------------------------

$l['contact'] = 'Contacteer Ons';
$l['contact_no_message'] = 'U heeft geen bericht ingevoerd om te verzenden.';
$l['contact_no_subject'] = 'U bent verplicht om een onderwerp op te geven.';
$l['contact_no_email'] = 'U moet een geldig e-mail adres opgeven.';
$l['contact_success_message'] = 'Uw bericht is succesvol verzonden naar de administrator.';
$l['contact_subject'] = 'Onderwerp';
$l['contact_subject_desc'] = 'Korte omschrijving van uw probleem.';
$l['contact_message'] = 'Bericht';
$l['contact_message_desc'] = 'Beschrijf hier uw probleem in detail.';
$l['contact_email'] = 'Email';
$l['contact_email_desc'] = 'Geef uw e-mail adres zodat we u kunnen beantwoorden.';
$l['contact_send'] = 'Stuur';
$l['subject_too_long'] = 'Het onderwerp is te lang. Geef alstublieft een onderwerp van maximaal {1} karakters (Op dit moment {2}).';
$l['message_too_short'] = 'Het bericht is te kort. Geef alstublieft een bericht op dat langer is dan {1} karakters (Op dit moment {2}).';
$l['message_too_long'] = 'Het bericht is te lang. eef alstublieft een bericht op dat korter is dan {1} karakters (Op dit moment {2}).';
$l['error_stop_forum_spam_spammer'] = 'Sorry, {1} matched met dat van een bekende spammer en daarom is uw bericht geblokkeerd.';
$l['error_stop_forum_spam_fetching'] = 'Sorry, er is iets misgegaan bij het controleren of uw e-mail adres dat van een spammer is. Waarschijnlijk kon de database niet benaderd worden. Probeer het alstublieft later opnieuw.';
