<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Fonta
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 18*
// Last edited in MyBB Editor by : Fonta
// Last edited date : Mon, 27 Jul 2020 10:12:20 +0000
// --------------------------------------------------------------------------------

$l['pmdata_too_long_subject'] = 'Het onderwerp voor uw persoonlijke bericht is te lang. Voer een korter onderwerp in.';
$l['pmdata_code_no_subject'] = '[geen onderwerp]';
$l['pmdata_missing_subject'] = 'U hebt geen onderwerp ingevoerd. Voer een onderwerp in.';
$l['pmdata_missing_message'] = 'U hebt geen bericht ingevoerd. Voer een bericht in.';
$l['pmdata_invalid_recipients'] = 'Een of meerdere geadresseerden bestaan niet. Ongeldige gebruikers: {1}';
$l['pmdata_no_recipients'] = 'U hebt geen geadresseerden ingevoerd. Voer minstens &eacute;&eacute;n geadresseerde in.';
$l['pmdata_too_many_recipients'] = 'U kunt een bericht naar maximaal {1} gebruikers tegelijk verzenden.';
$l['pmdata_recipient_is_ignoring'] = '{1} heeft u op zijn of haar negeerlijst staan. Uw bericht kan daarom niet worden verstuurd.';
$l['pmdata_recipient_has_buddy_only'] = '{1} heeft u niet in zijn of haar vriendenlijst staan. Uw bericht kan daarom niet worden verstuurd.';
$l['pmdata_recipient_pms_disabled'] = '{1} heeft het ontvangen van persoonlijke berichten uitgeschakeld. Uw bericht kan daarom niet worden verstuurd.';
$l['pmdata_recipient_reached_quota'] = '{1} kan geen persoonlijke berichten meer ontvangen omdat zijn of haar opslaglimiet voor persoonlijke berichten is bereikt. Uw bericht kan daarom niet worden verstuurd.';
$l['pmdata_pm_flooding'] = 'U kunt niet zo snel achter elkaar persoonlijke berichten verzenden. Wacht {1} seconden en probeer het dan opnieuw.';
$l['pmdata_pm_flooding_one_second'] = 'U kunt niet zo snel achter elkaar persoonlijke berichten verzenden. Wacht een seconde en probeer het dan opnieuw.';
$l['pmdata_message_too_long'] = 'Het bericht is te lang. Voer een bericht in dat korter is dan {1} karakters (Huidig: {2}). ';
