<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Fonta
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 02 Jun 2017 09:02:30 +0000
// --------------------------------------------------------------------------------

$l['userdata_missing_username'] = 'U hebt geen gebruikersnaam ingevoerd. Voer een gebruikersnaam in.';
$l['userdata_banned_username'] = 'De door u ingevoerde gebruikersnaam is ongeldig of bestaat niet. Voer een andere gebruikersnaam in.';
$l['userdata_bad_characters_username'] = 'De door u ingevoerde gebruikersnaam bevat tekens die niet zijn toegestaan. Voer een andere gebruikersnaam in.';
$l['userdata_invalid_username_length'] = 'De lengte van de door u ingevoerde gebruikersnaam is niet toegestaan. Voer een gebruikersnaam in van minimaal {1} en maximaal {2} tekens.';
$l['userdata_invalid_usertitle_length'] = 'De lengte van de door u ingevoegde aangepaste gebruikerstitel is niet toegestaan. Voer een gebruikerstitel in van maximaal {1} tekens.';
$l['userdata_username_exists'] = 'De door u ingevoerde gebruikersnaam bestaat al. Voer een andere gebruikersnaam in.';
$l['userdata_invalid_password_length'] = 'De lengte van het door u ingevoerde wachtwoord is niet toegestaan. Voer een wachtwoord in van minimaal {1} en maximaal {2} tekens.';
$l['userdata_no_complex_characters'] = 'Het wachtwoord dat u hebt ingevoerd, is niet sterk genoeg. Kies een wachtwoord dat ten minste {1} tekens telt en ten minste &eacute;&eacute;n hoofdletter, &eacute;&eacute;n kleine letter en &eacute;&eacute;n cijfer bevat.';
$l['userdata_passwords_dont_match'] = 'De twee wachtwoorden komen niet overeen. Voer uw wachtwoord opnieuw twee keer in.';
$l['userdata_bad_password_security'] = 'Het door u ingevulde wachtwoord is uw gebruikersnaam of uw e-mailadres. Vul alstublieft een sterker wachtwoord in.';
$l['userdata_missing_email'] = 'U hebt geen e-mailadres ingevoerd. Voer een e-mailadres in.';
$l['userdata_invalid_email_format'] = 'Het door u ingevoerde e-mailadres is ongeldig. Voer een geldig e-mailadres in.';
$l['userdata_emails_dont_match'] = 'De twee e-mailadressen komen niet overeen. Voer uw e-mailadres opnieuw twee keer in.';
$l['userdata_banned_email'] = 'Het door u ingevoerde e-mailadres is verboden. Voer een ander e-mailadres in.';
$l['userdata_email_already_in_use'] = 'Het door u ingevoerde e-mailadres wordt al gebruikt door een andere gebruiker. Voer een ander e-mailadres in.';
$l['userdata_dob_required'] = 'U hebt geen geboortedatum opgegeven. Voer uw geboortedatum in. Als u wilt, kunt u uw leeftijd en geboortedatum voor andere gebruikers verbergen.';
$l['userdata_invalid_website'] = 'De door u ingevoerde website is ongeldig. Voer een geldig adres in of laat het veld leeg.';
$l['userdata_invalid_icq_number'] = 'Het door u ingevoerde ICQ-nummer is ongeldig. Voer een geldig ICQ-nummer in of laat het veld leeg.';
$l['userdata_invalid_birthday'] = 'De door u ingevoerde geboortedatum is ongeldig. Voer een geldige geboortedatum in of laat het veld leeg.';
$l['userdata_invalid_birthday_coppa'] = 'Voer uw geboortejaar in, zodat uw leeftijd gecontroleerd kan worden. U kunt ervoor kiezen uw leeftijd en geboortedatum te verbergen in uw profielinstellingen.';
$l['userdata_invalid_birthday_coppa2'] = 'U moet minstens 13 jaar oud zijn om lid te mogen worden van dit forum. Neem contact op met een beheerder voor meer informatie.';
$l['userdata_invalid_birthday_privacy'] = 'Kies een geldige verjaardag privacy-optie.';
$l['userdata_invalid_referrer'] = 'De door u ingevoerde doorverwijzer bestaat niet. Voer de gebruikersnaam van een bestaand lid van dit forum in of laat het veld leeg.';
$l['userdata_invalid_language'] = 'De door u gekozen taal bestaat niet. Kies een bestaande taal.';
$l['userdata_missing_returndate'] = 'De door u opgegeven datum van terugkeer is niet juist ingevuld. Vul zowel de dag, de datum als het jaar in.';
$l['userdata_missing_required_profile_field'] = 'U hebt geen geldige optie gekozen voor het veld "{1}". Vul dit veld in of kies een geldige waarde voor dit veld.';
$l['userdata_bad_profile_field_value'] = 'U hebt geen geldige waarde ingevuld in het "{1}" veld . Vul alstublieft een geldige waarde in voordat u door gaat.';
$l['userdata_bad_profile_field_values'] = 'U hebt geen geldige optie gekozen voor het veld "{1}". Kies een geldige waarde voor dit veld.';
$l['userdata_max_limit_reached'] = 'De door u ingevoerde tekst in het tekstvak "{1}" is te lang. Gebruik niet meer dan {2} tekens.';
$l['userdata_invalid_checkfield'] = 'Dit formulier lijkt te zijn ingevuld door een spambot. Als u van mening bent dat dit onjuist is, neem dan contact op met een beheerder.';
$l['userdata_invalid_postnum'] = 'U hebt geen geldig aantal berichten ingevoerd. Voer een geldig aantal berichten in of laat het veld leeg.';
$l['userdata_invalid_threadnum'] = 'Het topic nummer dat u invulde is ongeldig. Vul alstublieft een geldige topic nummer in, of laat het veld leeg.';
$l['userdata_invalid_style'] = 'De door u geselecteerde stijl is foutief. Selecteer alstublieft een andere stijl';
$l['userdata_too_many_sig_images'] = 'U kunt uw handtekening niet bijwerken omdat er te veel afbeeldingen in zitten. Verwijder een aantal afbeeldingen en probeer opnieuw.';
$l['userdata_too_many_sig_images2'] = 'Het <strong>maximale</strong> aantal afbeeldingen in uw afbeelding is {1}';
$l['userdata_sig_too_long'] = 'U kunt uw handtekening niet bijwerken omdat het te lang is. Het maximale aantal karakters voor handtekeningen is {1}';
$l['userdata_sig_remove_chars_plural'] = 'Verwijder {1} karakters en probeer opnieuw.';
$l['userdata_sig_remove_chars_singular'] = 'Verwijder 1 karakter en probeer opnieuw.';
