<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 11:49:09 +0000
// --------------------------------------------------------------------------------

$l['eventdata_missing_name'] = 'Het onderwerp voor deze afspraak ontbreekt. Voer een onderwerp in.';
$l['eventdata_missing_description'] = 'De details voor deze afspraak ontbreken. Voer de details in.';
$l['eventdata_invalid_start_date'] = 'U hebt een ongeldige begindatum opgegeven. Voer een dag, maand en jaar in en controleer dat de opgegeven datum bestaat.';
$l['eventdata_invalid_start_year'] = 'U kunt alleen afspraken plaatsen op dagen in de komende vijf jaar. Geef een mogelijke begindatum op.';
$l['eventdata_invalid_start_month'] = 'U hebt een ongeldige begindatum opgegeven. Voer een geldige maand in.';
$l['eventdata_invalid_end_date'] = 'U hebt een ongeldige einddatum opgegeven. Voer een dag, maand en jaar in en controleer dat de opgegeven datum bestaat.';
$l['eventdata_invalid_end_year'] = 'U kunt alleen afspraken plaatsen op dagen in de komende vijf jaar. Geef een mogelijke einddatum op.';
$l['eventdata_invalid_end_month'] = 'U hebt een ongeldige einddatum opgegeven. Voer een geldige maand in.';
$l['eventdata_invalid_end_day'] = 'U hebt een ongeldige einddatum opgegeven. Controleer dat de opgegeven dag bestaat in de opgegeven maand.';
$l['eventdata_cant_specify_one_time'] = 'U moet een eindtijd opgeven.';
$l['eventdata_start_time_invalid'] = 'U hebt een ongeldige begintijd opgegeven. Mogelijke tijden zijn 12am, 12:01am en 00:01.';
$l['eventdata_end_time_invalid'] = 'U hebt een ongeldige eindtijd opgegeven. Mogelijke tijden zijn 12am, 12:01am en 00:01.';
$l['eventdata_invalid_timezone'] = 'U hebt een ongeldige tijdzone opgegeven.';
$l['eventdata_end_in_past'] = 'U hebt een einddatum of eindtijd opgegeven die plaatsvindt voor de begindatum of begintijd.';
$l['eventdata_only_ranged_events_repeat'] = 'Alleen meerdaagse afspraken kunnen terugkeren.';
$l['eventdata_invalid_repeat_day_interval'] = 'U hebt een ongeldig dagelijks terugkeerpatroon opgegeven.';
$l['eventdata_invalid_repeat_week_interval'] = 'U hebt een ongeldig wekelijks terugkeerpatroon opgegeven.';
$l['eventdata_invalid_repeat_weekly_days'] = 'U moet aangeven op welke dagen deze afspraak terugkeert.';
$l['eventdata_invalid_repeat_month_interval'] = 'U hebt een ongeldig maandelijks terugkeerpatroon opgegeven.';
$l['eventdata_invalid_repeat_year_interval'] = 'U hebt een ongeldig jaarlijks terugkeerpatroon opgegeven.';
$l['eventdata_event_wont_occur'] = 'U hebt een afspraak gemaakt die niet zal plaatsvinden. Controleer het terugkeerpatroon.';
$l['eventdata_no_permission_private_event'] = 'U mag geen persoonlijke afspraken plaatsen.';
