<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved.
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 11:49:37 +0000
// --------------------------------------------------------------------------------

$l['postdata_invalid_user_id'] = 'Het gebruikers-id bestaat niet. Voer een geldig gebruikers-id in.';
$l['postdata_firstpost_no_subject'] = 'Het onderwerp voor deze topic ontbreekt. Voer een onderwerp in.';
$l['postdata_missing_subject'] = 'Het onderwerp ontbreekt. Voer een onderwerp in.';
$l['postdata_missing_message'] = 'U hebt geen bericht ingevoerd. Voer een bericht in.';
$l['postdata_message_too_long'] = 'Uw bericht is te lang. U hebt momenteel {2} tekens gebruikt, maar u mag er maar {1} gebruiken.';
$l['postdata_message_too_short'] = 'Uw bericht is te kort. U moet minstens {1} tekens gebruiken.';
$l['postdata_subject_too_long'] = 'Uw onderwerp is te lang. U hebt momenteel {1} tekens gebruikt, maar u mag er maar 85 gebruiken.';
$l['postdata_banned_username'] = 'De gebruikersnaam die u heeft gekozen mag niet gebruikt worden. Vul alstublieft een andere gebruikersnaam in.';
$l['postdata_bad_characters_username'] = 'De door u ingevulde gebruikersnaam bevat verkeerde karakters. Vul alstublieft een andere gebruikersnaam in.';
$l['postdata_invalid_username_length'] = 'De door u ingevulde gebruikersnaam heeft een foutieve lengte.Vul alstublieft een gebruikersnaam in van tussen de {1} en {2} karakters.';
$l['postdata_post_flooding'] = 'U mag niet zo snel na het plaatsen van een bericht opnieuw een bericht plaatsen. U kunt weer berichten plaatsen over {1} seconden.';
$l['postdata_post_flooding_one_second'] = 'U mag niet zo snel na het plaatsen van een bericht opnieuw een bericht plaatsen. U kunt weer berichten plaatsen over één seconde.';
$l['postdata_too_many_images'] = 'Uw bericht bevat {1} afbeeldingen, maar berichten mogen slechts {2} afbeeldingen bevatten. Verwijder enkele afbeeldingen uit uw bericht en probeer het opnieuw.';
$l['postdata_too_many_videos'] = 'Uw bericht bevat {1} videos, maar berichten mogen slechts {2} bevatten. Verwijder enkele videos uit uw bericht en probeer het opnieuw.';
$l['postdata_invalid_prefix'] = 'De geselecteerde prefix is foutief. Selecteer alstublieft een valide prefix.';
$l['postdata_require_prefix'] = 'In dit forum is een prefix verplicht. Selecteer alstublieft een valide prefix.';
$l['thread_closed'] = 'Topic is gesloten';
$l['thread_opened'] = 'Topic is geopend';
$l['thread_stuck'] = 'Topic is belangrijk gemaakt';
$l['thread_unstuck'] = 'Topic is onbelangrijk gemaakt';
$l['postdata_username_exists'] = 'De opgegeven gebruikersnaam bestaat niet. Voer alstublieft een andere naam in.';
