<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 11:50:03 +0000
// --------------------------------------------------------------------------------

$l['warnings_reached_max_warnings_day'] = 'U kunt niemand meer waarschuwen omdat u het maximale aantal waarschuwingen per dag hebt bereikt.<br /><br />Het maximaal {1} waarschuwingen per dag geven ."';
$l['warnings_error_invalid_user'] = 'De geselecteerde gebruiker bestaat niet.';
$l['warnings_error_invalid_post'] = 'Het geselecteerde bericht bestaat niet.';
$l['warnings_error_cannot_warn_self'] = 'U kunt u zelf niet waarschuwen.';
$l['warnings_error_user_reached_max_warning'] = 'Deze gebruiker kan niet meer gewaarschuwd worden omdat deze het maximale level reeds heeft bereikt.';
$l['warnings_error_no_note'] = 'U heeft geen notitie opgegeven bij de waarschuwing.';
$l['warnings_error_invalid_type'] = 'U heeft een invalide waarschuwings type gekozen.';
$l['warnings_error_cant_custom_warn'] = 'U heeft geen autorisaties om cutom waarschuwingen aan gebruikers te geven.';
$l['warnings_error_no_custom_reason'] = 'U heeft geen reden opgegeven in de custom waarschuwing.';
$l['warnings_error_invalid_custom_points'] = 'U heeft geen valide waarschuwings puntenaantal opgegeven. Geef alstublieft een numeriek aantal op dat hoger is dan 0 maar lager dan {1}';
$l['warnings_error_invalid_expires_period'] = 'U heeft een invalide afloop type opgegeven.';
