<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved.
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 11:49:16 +0000
// --------------------------------------------------------------------------------

$l['logindata_invalidpwordusername'] = 'U heeft een foutieve naam/wachtwoord combinatie opgegeven. <br /><br />Als u uw wachtwoord bent vergeten haal dan <a href="member.php?action=lostpw">een nieuwe op</a>.';
$l['logindata_invalidpwordusernameemail'] = 'U heeft een foutieve email/wachtwoord combinatie opgegeven. <br /><br />Als u uw wachtwoord bent vergeten haal dan <a href="member.php?action=lostpw">een nieuwe op</a>.';
$l['logindata_invalidpwordusernamecombo'] = 'U heeft een foutieve naam/wachtwoord of email/wachtwoord combinatie opgegeven. <br /><br />Als u uw wachtwoord bent vergeten haal dan <a href="member.php?action=lostpw">een nieuwe op</a>.';
$l['logindata_regimageinvalid'] = 'De afbeeldings verificatie code die u heeft ingevuld was foutief. Vul alstublieft de code exact in zoals op de afbeelding.';
$l['logindata_regimagerequired'] = 'Voer alstublieft de afbeeldings verificatie code in om verder te gaan met inloggen. Vul alstublieft de code exact in zoals op de afbeelding.';
