<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved.
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 11:50:13 +0000
// --------------------------------------------------------------------------------

$l['nav_editpost'] = 'Bericht bewerken';
$l['edit_post'] = 'Bericht bewerken';
$l['delete_post'] = 'Bericht verwijderen';
$l['delete_q'] = 'Verwijderen?';
$l['delete_1'] = 'Vink het keuzevakje links aan en klik op de knop rechts om dit bericht te verwijderen.';
$l['delete_2'] = '<b>Opmerking</b>: hiermee zal het hele topic verwijderd worden als dit bericht het eerste bericht in een topic is.';
$l['subject'] = 'Onderwerp:';
$l['your_message'] = 'Bericht';
$l['post_options'] = 'Berichtopties:';
$l['editreason'] = 'Bewerk reden:';
$l['options_sig'] = '<strong>Handtekening</strong>: hiermee wordt uw handtekening bijgevoegd (alleen voor geregistreerde gebruikers).';
$l['options_emailnotify'] = '<strong>E-mailmelding:</strong> hiermee ontvangt u een e-mailbericht zodra er een nieuwe reactie is geplaatst (alleen voor geregistreerde gebruikers).';
$l['options_disablesmilies'] = '<strong>Emoticons uitschakelen</strong>: hiermee voorkomt u dat emoticons in dit bericht worden weergegeven.';
$l['preview_post'] = 'Voorbeeld weergeven';
$l['update_post'] = 'Bericht bijwerken';
$l['poll'] = 'Peiling:';
$l['poll_desc'] = 'U kunt een peiling aan dit topic toevoegen.';
$l['poll_check'] = 'Een peiling aan dit topic toevoegen';
$l['num_options'] = 'Aantal keuzes:';
$l['max_options'] = '(maximaal {1})';
$l['delete_now'] = 'Verwijderen';
$l['edit_time_limit'] = 'U kunt uw bericht niet bewerken. Een beheerder heeft ervoor gezorgd dat berichten alleen kunnen worden bewerkt binnen {1} minuten na het plaatsen ervan.';
$l['no_prefix'] = 'Geen voorvoegsel';
$l['redirect_nodelete'] = 'Het bericht is niet verwijderd, omdat u het keuzevakje niet had aangevinkt.';
$l['redirect_norestore'] = 'Het bericht is niet hersteld, omdat u het keuzevakje niet had aangevinkt.';
$l['redirect_postedited'] = 'Het bericht is bewerkt.<br />';
$l['redirect_postedited_redirect'] = 'U zult nu worden teruggebracht naar de topic.';
$l['redirect_postedited_poll'] = 'Het bericht is bewerkt.<br />U zult nu naar de pagina met peilingopties en -instellingen worden gebracht.';
$l['error_invalidpost'] = 'Het bericht dat u wilt bewerken, lijkt niet te bestaan. Controleer dat het bericht bestaat en probeer het opnieuw.';
$l['redirect_threaddeleted'] = 'He topic is verwijderd.<br />U zult nu worden teruggebracht naar het forum.';
$l['redirect_postdeleted'] = 'Het bericht is verwijderd.<br />U zult nu worden teruggebracht naar het topic.';
$l['redirect_threadrestored'] = 'Dank u, het topic is hersteld.<br />U zult nu worden teruggebracht naar het forum.';
$l['redirect_postrestored'] = 'Dank u, het bericht is hersteld.<br />U zult nu worden teruggebracht naar het topic.';
$l['redirect_threadclosed'] = 'U kunt in dit topic geen reacties plaatsen of bestaande berichten bewerken omdat dit topic is gesloten door een moderator.';
$l['redirect_post_moderation'] = 'De beheerder heeft ingesteld dat alle berichten na bewerking goedgekeurd moeten worden.<br />U zult nu worden teruggebracht naar het topic.';
$l['redirect_thread_moderation'] = 'De beheerder heeft ingesteld dat alle topics na bewerking goedgekeurd moeten worden.<br />U zult nu worden teruggebracht naar het forum.';
$l['error_already_delete'] = 'Sorry, maar dit bericht is reeds verwijderd.';
$l['thread_deleted'] = 'Verwijderd topic';
$l['post_deleted'] = 'Verwijderd bericht';
$l['thread_soft_deleted'] = 'Voorlopig verwijderd topic';
$l['post_soft_deleted'] = 'Voorlopig verwijderd bericht';
$l['thread_restored'] = 'Hersteld topic';
$l['post_restored'] = 'Hersteld bericht';
$l['error_already_deleted'] = 'Het geselecteerde bericht is reeds verwijderd.';
