<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved.
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 11:50:29 +0000
// --------------------------------------------------------------------------------

$l['post_thread'] = 'Nieuw topic plaatsen';
$l['moderated_by'] = 'Dit forum wordt gemodereerd door:';
$l['nothreads'] = 'Er zijn momenteel geen topics in dit forum die voldoen aan de opgegeven datum- en tijdscriteria.';
$l['search_forum'] = 'Dit forum doorzoeken:';
$l['thread'] = 'Topic';
$l['author'] = 'Auteur';
$l['replies'] = 'Reacties';
$l['views'] = 'Weergaven';
$l['lastpost'] = 'Laatste bericht';
$l['rating'] = 'Waardering';
$l['prefix'] = 'Prefix:';
$l['prefix_all'] = 'Prefix: Alle/Geen Prefixen';
$l['markforum_read'] = 'Dit forum als gelezen markeren';
$l['subscribe_forum'] = 'Op dit forum abonneren';
$l['unsubscribe_forum'] = 'Abonnement op dit forum opzeggen';
$l['clear_stored_password'] = 'Opgeslagen wachtwoord voor forum verwijderen';
$l['sort_by_subject'] = 'Sorteren op onderwerp';
$l['sort_by_lastpost'] = 'Sorteren op datum laatste bericht';
$l['sort_by_starter'] = 'Sorteren op auteur';
$l['sort_by_started'] = 'Sorteren op datum eerste bericht';
$l['sort_by_rating'] = 'Sorteren op waardering';
$l['sort_by_replies'] = 'Sorteren op aantal reacties';
$l['sort_by_views'] = 'Sorteren op aantal weergaven';
$l['sort_order_asc'] = 'in oplopende volgorde';
$l['sort_order_desc'] = 'in aflopende volgorde';
$l['datelimit_1day'] = 'en alleen topics van vandaag weergeven';
$l['datelimit_5days'] = 'en alleen topics van de afgelopen 5 dagen weergeven';
$l['datelimit_10days'] = 'en alleen topics van de afgelopen 10 dagen weergeven';
$l['datelimit_20days'] = 'en alleen topics van de afgelopen 20 dagen weergeven';
$l['datelimit_50days'] = 'en alleen topics van de afgelopen 50 dagen weergeven';
$l['datelimit_75days'] = 'en alleen topics van de afgelopen 75 dagen weergeven';
$l['datelimit_100days'] = 'en alleen topics van de afgelopen 100 dagen weergeven';
$l['datelimit_lastyear'] = 'en alleen topics van het afgelopen jaar weergeven';
$l['datelimit_beginning'] = 'en alle topics weergeven';
$l['new_thread'] = 'Bevat nieuwe berichten';
$l['new_hot_thread'] = 'Populair topic (recent)';
$l['posts_by_you'] = 'Bevat berichten van u';
$l['no_new_thread'] = 'Bevat geen nieuwe berichten';
$l['hot_thread'] = 'Populair topic (niet recent)';
$l['locked_thread'] = 'Topic is gesloten';
$l['goto_first_unread'] = 'Naar eerste ongelezen bericht gaan';
$l['pages'] = 'Pagina\'s:';
$l['pages_last'] = 'laatste';
$l['users_browsing_forum'] = 'Gebruikers die dit forum bekijken:';
$l['users_browsing_forum_guests'] = '{1} gasten';
$l['users_browsing_forum_invis'] = '{1} onzichtbare leden';
$l['delayed_moderation'] = 'Uitgestelde moderatie';
$l['inline_thread_moderation'] = 'topicmoderatie:';
$l['close_threads'] = 'Sluiten';
$l['open_threads'] = 'Openen';
$l['stick_threads'] = 'Belangrijk maken';
$l['unstick_threads'] = 'Onbelangrijk maken';
$l['soft_delete_threads'] = 'Voorlopig verwijderen';
$l['restore_threads'] = 'Herstellen';
$l['delete_threads'] = 'Definitief verwijderen';
$l['move_threads'] = 'Verplaatsen';
$l['approve_threads'] = 'Goedkeuren';
$l['unapprove_threads'] = 'Afkeuren';
$l['inline_go'] = 'Uitvoeren';
$l['clear'] = 'Selectie opheffen';
$l['sub_forums_in'] = 'Forums in {1}';
$l['forum_rules'] = 'Regels voor {1}';
$l['subforums'] = '<strong>Subforums:</strong>';
$l['asc'] = 'opl';
$l['desc'] = 'afl';
$l['forum_announcements'] = 'Aankondiging';
$l['sticky_threads'] = 'Belangrijk topic';
$l['normal_threads'] = 'Normaal topic';
$l['icon_dot'] = 'Bevat berichten van u. ';
$l['icon_no_new'] = 'Bevat geen nieuwe berichten.';
$l['icon_new'] = 'Bevat nieuwe berichten.';
$l['icon_hot'] = ' Populair topic (recent).';
$l['icon_lock'] = ' Topic is gesloten.';
$l['attachment_count'] = 'Dit topic bevat &eacute;&eacute;n bijlage';
$l['attachment_count_multiple'] = 'Dit topic bevat {1} bijlagen';
$l['rss_discovery_forum'] = 'Laatste topics in {1}';
$l['forum_unapproved_posts_count'] = 'Dit forum bevat {1} nog niet goedgekeurde berichten.';
$l['forum_unapproved_post_count'] = 'Dit forum bevat &eacute;&eacute;n nog niet goedgekeurd bericht.';
$l['forum_unapproved_threads_count'] = 'Dit forum bevat {1} nog niet goedgekeurde topics.';
$l['forum_unapproved_thread_count'] = 'Dit forum bevat &eacute;&eacute;n nog niet goedgekeurd topic.';
$l['thread_unapproved_posts_count'] = 'Dit topic bevat {1} nog niet goedgekeurde berichten.';
$l['thread_unapproved_post_count'] = 'Dit topic bevat &eacute;&eacute;n nog niet goedgekeurd bericht.';
$l['page_selected'] = 'Alle <strong>{1}</strong> topics op deze pagina zijn geselecteerd.';
$l['all_selected'] = 'Alle <strong>{1}</strong> topics in dit forum zijn geselecteerd.';
$l['select_all'] = 'Alle <strong>{1}</strong> topics in dit forum selecteren';
$l['clear_selection'] = 'Selectie ongedaan maken';
$l['error_containsnoforums'] = 'Het huidige forum bevat geen subforums.';
$l['inline_edit_description'] = '(Klik en hou vast om te bewerken)';
$l['prefix_any'] = 'Prefix: Alle Prefixen';
$l['prefix_none'] = 'Prefix: Geen Prefix';
