<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1801
// Last edited in MyBB Editor by : Fonta
// Last edited date : Thu, 03 Dec 2015 05:29:48 +0000
// --------------------------------------------------------------------------------

$l['hello'] = 'Hallo Wereld!';
$l['hello_add'] = 'Toevoegen';
$l['hello_add_message'] = 'Bericht Toevoegen';
$l['hello_empty'] = 'Geen berichten gevonden.';
$l['hello_message_empty'] = 'Bericht mag niet leeg zijn.';
$l['hello_done'] = 'Bericht succesvol toegevoegd.';
