<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved.
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 11:58:16 +0000
// --------------------------------------------------------------------------------

$l['s1_name'] = 'Gebruikers beheer';
$l['s1_desc'] = 'Basis instructies voor het beheren van een forum account.';
$l['s2_name'] = 'Posten';
$l['s2_desc'] = 'Posten, antwoorden, en basis gebruik van het forum.';
