<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved.
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 11:58:38 +0000
// --------------------------------------------------------------------------------

$l['error_no_connection'] = 'De verbinding met de server kon niet tot stand worden gebracht: ';
$l['error_no_message'] = 'U hebt geen bericht opgegeven.';
$l['error_no_subject'] = 'U hebt geen onderwerp opgegeven.';
$l['error_no_recipient'] = 'U hebt geen ontvanger opgegeven.';
$l['error_not_sent'] = 'Er is een fout opgetreden bij het versturen van het e-mailbericht met de PHP-mailfunctie.';
$l['error_status_missmatch'] = 'De status van de server is verschillend van de verwachte status. De status van de server is: ';
$l['error_data_not_sent'] = 'Deze gegevens konden niet worden verzonden naar de server: ';
$l['error_occurred'] = 'E&eacute;n of meerdere fouten zijn opgetreden. Verhelp de volgende fouten voordat u verdergaat.<br />';
