<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved.
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 11:58:48 +0000
// --------------------------------------------------------------------------------

$l['nav_group_management'] = 'Groep {1} beheren';
$l['nav_join_requests'] = 'Lidmaatschapsverzoeken';
$l['nav_group_memberships'] = 'Groepen beheren';
$l['not_leader_of_this_group'] = 'U bent geen leider van deze gebruikersgroep.';
$l['invalid_group'] = 'Deze gebruikersgroep bestaat niet.';
$l['pending_requests'] = 'Lidmaatschapsverzoeken';
$l['num_requests_pending'] = 'Er zijn momenteel <strong>{1}</strong> lidmaatschapsverzoeken voor deze gebruikersgroep.';
$l['group_management'] = 'Groepen beheren';
$l['members_of'] = 'Leden in {1}';
$l['user_name'] = 'Gebruikersnaam';
$l['contact'] = 'Contact opnemen';
$l['reg_date'] = 'Lid sinds';
$l['post_count'] = 'Aantal berichten';
$l['remove_selected'] = 'Geselecteerde gebruikers uit groep verwijderen';
$l['add_member'] = 'Gebruiker aan groep {1} toevoegen';
$l['add_member_submit'] = 'Gebruiker aan groep toevoegen';
$l['invite_member'] = 'Invite Member to "{1}"';
$l['invite_member_submit'] = 'Invite Member to Group';
$l['join_requests'] = 'Lidmaatschapsverzoeken';
$l['join_requests_title'] = 'Lidmaatschapsverzoeken voor {1}';
$l['leader'] = '(groepsleider)';
$l['reason'] = 'Reden';
$l['accept'] = 'Goedkeuren';
$l['ignore'] = 'Negeren';
$l['decline'] = 'Afwijzen';
$l['action_requests'] = 'Lidmaatschapsverzoeken verwerken';
$l['join_requests_moderated'] = 'De lidmaatschapsverzoeken zijn verwerkt.<br />U zult nu naar de opgegeven lijst worden gebracht.';
$l['no_requests'] = 'Er zijn momenteel geen lidmaatschapsverzoeken voor deze groep.';
$l['no_users'] = 'Er zijn geen leden in deze groep.';
$l['user_added'] = 'De gebruiker is aan de gebruikersgroep toegevoegd.';
$l['users_removed'] = 'De geselecteerde gebruikers zijn uit de gebruikersgroep verwijderd.';
$l['group_no_members'] = 'Er bevinden zich momenteel geen gebruikers in deze groep.<br />Klik <a href="usercp.php?action=usergroups">hier</a> om terug te keren naar de pagina Groepen beheren.';
$l['group_public_moderated'] = 'Deze gebruikersgroep is een openbare groep, waardoor iedereen er lid van kan worden. Alle lidmaatschapsverzoeken dienen te worden goedgekeurd door een groepsleider.';
$l['group_public_not_moderated'] = 'Deze gebruikersgroep is een openbare groep, waardoor iedereen er lid van kan worden. Lidmaatschapsverzoeken hoeven niet te worden goedgekeurd.';
$l['group_public_invite'] = 'Deze gebruikersgroep is een besloten groep. Alleen groepsleiders kunnen gebruikers aan deze groep toevoegen.';
$l['group_private'] = 'Deze groep is prive.  Alleen gebruikers die zijn toegevoegd door de groeps kunnen hier lid van zijn.';
$l['group_default'] = 'Deze gebruikersgroep is een standaardgroep.';
$l['group_leaders'] = 'Groepsleiders';
$l['search_user'] = 'Zoek naar een gebruiker';
$l['no_users_selected'] = 'U hebt geen gebruikers geselecteerd om uit deze groep te verwijderen.<br />Ga terug en selecteer de gebruikers die u uit deze groep wilt verwijderen.';
$l['error_alreadyingroup'] = 'Deze gebruiker bevindt zich al in deze gebruikersgroep.';
$l['error_alreadyinvited'] = 'De opgegeven gebruiker is reeds uitgenodigd.';
$l['user_invited'] = 'De gebruiker is uitgenodigd om lid te worden van de groep.';
$l['invite_pm_subject'] = 'Je bent uitgenodigd om lid te worden van de groep "{1}"';
$l['invite_pm_message'] = 'Je hebt een uitnodiging ontvangen om lid te worden van de groep "{1}".

Om lid te worden, ga naar de [url={2}/usercp.php?action=usergroups]Groeps Lidmaatschappen[/url] pagina en klik op \'Accepteer Uitnoding\'.

Deze uitnodiging verloopt niet.';
$l['invite_pm_message_expires'] = 'Je bent uitgenodigd om lid te worden van de groep "{1}".

Om lid te worden, ga naar de [url={2}/usercp.php?action=usergroups]Groeps Lidmaatschappen[/url] pagina en klik op \'Accepteer Uitnoding\'.

Deze uitnodiging verloopt over {3} dagen vanaf nu.';
