<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 12:00:09 +0000
// --------------------------------------------------------------------------------

$l['nav_memberlist'] = 'Ledenlijst';
$l['memberlist_disabled'] = 'U kunt de ledenlijst niet gebruiken, omdat een beheerder deze mogelijkheid heeft uitgeschakeld.';
$l['member_list'] = 'Ledenlijst';
$l['avatar'] = 'Avatar';
$l['username'] = 'Gebruikersnaam';
$l['joined'] = 'Lid sinds';
$l['lastvisit'] = 'Laatste bezoek';
$l['posts'] = 'Berichten';
$l['threads'] = 'Topics';
$l['referrals'] = 'Doorverwijzingen';
$l['search_members'] = 'Zoek ledenlijst';
$l['website'] = 'Website';
$l['sort_by'] = 'Sorteren';
$l['contains'] = 'Bevat:';
$l['sort_by_username'] = 'Sorteren op gebruikersnaam';
$l['sort_by_regdate'] = 'Sorteren op datum van registratie';
$l['sort_by_lastvisit'] = 'Sorteren op laatste bezoek';
$l['sort_by_posts'] = 'Sorteren op aantal berichten';
$l['sort_by_threads'] = 'Sorteren op topic aantal';
$l['sort_by_referrals'] = 'Sorteren op doorverwijzingen';
$l['order_asc'] = 'in oplopende volgorde';
$l['order_desc'] = 'in aflopende volgorde';
$l['asc'] = 'asc';
$l['desc'] = 'desc';
$l['forumteam'] = 'Forumteam weergeven';
$l['advanced_search'] = 'Geavanceerd zoeken';
$l['nav_memberlist_search'] = 'Zoeken';
$l['search_member_list'] = 'Ledenlijst doorzoeken';
$l['search_criteria'] = 'Zoekcriteria';
$l['begins_with'] = 'begint met';
$l['username_contains'] = 'bevat';
$l['search_website'] = 'Locatie van website';
$l['search_aim'] = 'AIM-schermnaam';
$l['search_skype'] = 'Skype Address';
$l['search_google'] = 'Google Talk Address';
$l['search_yahoo'] = 'Yahoo! ID';
$l['search_icq'] = 'ICQ-nummer';
$l['search_options'] = 'Zoekopties';
$l['per_page'] = 'Aantal resultaten per pagina';
$l['search'] = 'Zoeken';
$l['search_user'] = 'Zoeken naar een gebruiker';
$l['error_no_members'] = '<p>Er zijn geen gebruikers gevonden die voldoen aan de opgegeven zoekcriteria.</p><p>Voer een nieuwe zoekopdracht in en probeer het opnieuw.</p>';
$l['a'] = 'A';
$l['b'] = 'B';
$l['c'] = 'C';
$l['d'] = 'D';
$l['e'] = 'E';
$l['f'] = 'F';
$l['g'] = 'G';
$l['h'] = 'H';
$l['i'] = 'I';
$l['j'] = 'J';
$l['k'] = 'K';
$l['l'] = 'L';
$l['m'] = 'M';
$l['n'] = 'N';
$l['o'] = 'O';
$l['p'] = 'P';
$l['q'] = 'Q';
$l['r'] = 'R';
$l['s'] = 'S';
$l['t'] = 'T';
$l['u'] = 'U';
$l['v'] = 'V';
$l['w'] = 'W';
$l['x'] = 'X';
$l['y'] = 'Y';
$l['z'] = 'Z';
