<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved.
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 12:01:39 +0000
// --------------------------------------------------------------------------------

$l['nav_helpdocs'] = 'Help-onderwerpen';
$l['nav_smilies'] = 'Lijst met emoticons';
$l['nav_syndication'] = 'Syndicatie laatste topics (RSS)';
$l['aol_im'] = 'AOL';
$l['skype'] = 'Skype';
$l['yahoo_im'] = 'Yahoo IM';
$l['skype_center'] = 'Skype Center';
$l['skype_status'] = 'Skype Status';
$l['chat_on_skype'] = 'Chat with {1} on Skype';
$l['call_on_skype'] = 'Call {1} on Skype';
$l['yahoo_center'] = 'Yahoo!';
$l['send_y_message'] = '{1} een Yahoo!-bericht sturen';
$l['view_y_profile'] = 'Het Yahoo!-profiel van {1} bekijken';
$l['aim_center'] = 'AOL';
$l['download_aim'] = 'AOL Instant Messager downloaden';
$l['aim_remote'] = 'AIM Remote';
$l['send_me_instant'] = 'Mij een instant messaging-bericht sturen';
$l['add_me_buddy_list'] = 'Mij aan uw vriendenlijst toevoegen';
$l['add_remote_to_page'] = 'Remote aan uw pagina toevoegen';
$l['download_aol_im'] = 'AOL Instant Messager downloaden';
$l['buddy_list'] = 'Buddylijst';
$l['online'] = 'Online';
$l['online_none'] = '<em>Je hebt geen buddies die online zijn</em>';
$l['offline'] = 'Offline';
$l['offline_none'] = '<em>Je hebt geen buddies die offline zijn</em>';
$l['delete_buddy'] = 'X';
$l['pm_buddy'] = 'Een persoonlijk bericht sturen';
$l['last_active'] = '<strong>Laatst actief:</strong> {1}';
$l['close'] = 'Venster sluiten';
$l['no_buddies'] = '<em>Uw vriendenlijst is leeg. U kunt gebruikers toevoegen aan uw vriendenlijst via hun profiel of uw GebruikersCS.</em>';
$l['help_docs'] = 'Help-onderwerpen';
$l['search_help_documents'] = 'Zoek Hulp Documenten';
$l['search_by_name'] = 'Zoek op Naam';
$l['search_by_document'] = 'Zoek naar Document';
$l['enter_keywords'] = 'Zoekwoorden';
$l['search'] = 'Zoeken';
$l['redirect_searchresults'] = 'Dank u, uw zoekopdracht is verwerkt en u zult nu naar de resultaten gebracht worden.';
$l['search_results'] = 'Zoek Resultaten';
$l['help_doc_results'] = 'Hulp Document Resultaten';
$l['document'] = 'Document';
$l['error_nosearchresults'] = 'Sorry, er zijn geen resultaten gevonden. Pas uw zoektermen aan en probeer opnieuw.';
$l['no_help_results'] = 'Sorry, er zijn geen resultaten gevonden.';
$l['error_helpsearchdisabled'] = 'Het zoeken naar hulpdocumenten is uitgeschakeld door een administrator.';
$l['smilies_listing'] = 'Lijst met emoticons';
$l['name'] = 'Naam';
$l['abbreviation'] = 'Afkorting';
$l['click_to_add'] = 'Klik op een emoticon om deze in uw bericht in te voegen.';
$l['close_window'] = 'venster sluiten';
$l['who_posted'] = 'Wie heeft er een bericht geplaatst?';
$l['total_posts'] = 'Totaal aantal berichten:';
$l['user'] = 'Gebruiker';
$l['num_posts'] = 'Aantal';
$l['forum_rules'] = 'Regels voor {1}';
$l['error_invalid_limit'] = 'Het door u opgegeven aantal topics per keer is ongeldig. Voer een geldig aantal in.';
$l['syndication'] = 'Syndicatie laatste topics (RSS)';
$l['syndication_generated_url'] = 'Uw aangemaakte syndicatie-URL:';
$l['syndication_note'] = 'Hieronder kunt u koppelingen naar specifieke RSS-feeds aanmaken. Koppelingen kunnen worden aangemaakt voor alle forums, per forum of voor een specifiek aantal forums. U zult dan een koppeling toegewezen krijgen die u naar een RSS-lezer als <a href="http://www.sharpreader.net/">SharpReader</a> kunt kopi&euml;ren. <i><a href="http://nl.wikipedia.org/wiki/RSS">Meer informatie over RSS kunt u hier vinden.</a></i>';
$l['syndication_forum'] = 'Forum voor syndicatie:';
$l['syndication_forum_desc'] = 'Kies een forum uit de lijst rechts. Gebruik de Control-toets om meerdere forums te selecteren.';
$l['syndication_version'] = 'Versie RSS-feed:';
$l['syndication_version_desc'] = 'Kies welke versie feed u wilt aanmaken.';
$l['syndication_version_atom1'] = 'Atom 1.0';
$l['syndication_version_rss2'] = 'RSS 2.00 (standaard)';
$l['syndication_generate'] = 'Syndicatie-URL aanmaken';
$l['syndication_limit'] = 'Aantal topics per keer:';
$l['syndication_limit_desc'] = 'Het aantal topics dat per keer wordt gedownload. Een waarde hoger dan 50 wordt afgeraden.';
$l['syndication_threads_time'] = 'topics per keer';
$l['syndicate_all_forums'] = 'Alle forums syndiceren';
$l['redirect_markforumread'] = 'Het geselecteerde forum is als gelezen gemarkeerd.';
$l['redirect_markforumsread'] = 'Alle forums zijn als gelezen gemarkeerd.';
$l['redirect_forumpasscleared'] = 'Het wachtwoord dat voor dit forum was opgeslagen, is verwijderd.';
$l['redirect_cookiescleared'] = 'Alle cookies zijn gewist.';
$l['error_invalidimtype'] = 'Deze gebruiker heeft geen account voor dit type instant messaging opgegeven.';
$l['error_invalidhelpdoc'] = 'Het door u opgegeven help-onderwerp lijkt niet te bestaan.';
$l['error_invalidkey'] = 'U bent niet gemachtigd om de cookies te wissen. Dit kan komen doordat een kwaadaardig JavaScript probeerde automatisch uw cookies te wissen. Als u echt uw cookies wilt wissen, bekijk dan het helpdocument "Cookies"';
$l['dst_settings_updated'] = 'Uw zomertijdinstellingen zijn automatisch aangepast.<br /><br />U zult nu worden teruggebracht naar de beginpagina.';
