<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved.
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 12:03:46 +0000
// --------------------------------------------------------------------------------

$l['nav_newreply'] = 'Nieuwe reactie plaatsen';
$l['post_reply_to'] = 'Nieuwe reactie op topic {1}';
$l['post_new_reply'] = 'Nieuwe reactie plaatsen';
$l['reply_to'] = 'Nieuwe reactie op topic {1}';
$l['post_subject'] = 'Onderwerp:';
$l['your_message'] = 'Bericht:';
$l['post_options'] = 'Berichtopties:';
$l['options_sig'] = '<strong>Handtekening</strong>: hiermee wordt uw handtekening bijgevoegd (alleen voor geregistreerde gebruikers).';
$l['options_emailnotify'] = '<strong>E-mailmelding:<strong> hiermee ontvangt u een e-mailbericht zodra er een nieuwe reactie is geplaatst (alleen voor geregistreerde gebruikers).';
$l['options_disablesmilies'] = '<strong>Emoticons uitschakelen</strong>: hiermee voorkomt u dat emoticons in dit bericht worden weergegeven.';
$l['post_reply'] = 'Reactie plaatsen';
$l['preview_post'] = 'Voorbeeld weergeven';
$l['mod_options'] = 'Moderatoropties:';
$l['close_thread'] = '<strong>Topic sluiten</strong>: hiermee voorkomt u het plaatsen van verdere berichten in dit topic.';
$l['stick_thread'] = '<strong>Topic belangrijk maken</strong>: hiermee plaatst u dit topic bovenaan in de lijst met topic.';
$l['forum_rules'] = '{1} - Regels';
$l['thread_review'] = 'Topic-overzicht (meest recente berichten eerst)';
$l['thread_review_more'] = 'Dit topic bestaat uit meer dan {1} berichten. <a href="showthread.php?tid={2}">Het hele topic weergeven</a>.';
$l['posted_by'] = 'Geplaatst door';
$l['draft_saved'] = 'Uw reactie is als concept opgeslagen.<br />U zult nu naar de lijst met concepten worden gebracht.';
$l['image_verification'] = '';
$l['verification_note'] = '';
$l['verification_subnote'] = '';
$l['invalid_captcha'] = '';
$l['error_post_already_submitted'] = 'U hebt deze reactie al geplaatst. Ga naar het topic om uw reactie te bekijken.';
$l['multiquote_external_one'] = 'U hebt &eacute;&eacute;n bericht uit een ander topic geselecteerd.';
$l['multiquote_external'] = 'U hebt {1} berichten uit een ander topic geselecteerd.';
$l['multiquote_external_one_deselect'] = 'selectie van dit bericht opheffen.';
$l['multiquote_external_deselect'] = 'selectie van deze berichten opheffen.';
$l['multiquote_external_one_quote'] = 'Dit bericht ook citeren';
$l['multiquote_external_quote'] = 'Deze berichten ook citeren';
$l['redirect_newreply'] = 'Uw reactie is geplaatst.';
$l['redirect_newreply_moderation'] = 'De beheerder heeft aangegeven dat alle nieuwe berichten dienen te worden goedgekeurd.<br />U zult nu worden teruggebracht naar het topic.';
$l['redirect_newreply_post'] = '<br />U zult nu naar uw bericht worden gebracht.';
$l['redirect_newreplyerror'] = 'Uw reactie is geweigerd wegens gebrek aan inhoud.<br />U zult nu worden teruggebracht naar het topic.';
$l['redirect_threadclosed'] = 'U kunt in dit topic geen reacties plaatsen of bestaande berichten bewerken omdat dit topic is gesloten door een moderator.';
$l['error_post_noperms'] = 'U hebt niet de rechten om dit concept te mogen bewerken.';
$l['error_stop_forum_spam_spammer'] = 'Sorry, uw gebruikersnaam of IP adres matchen met dat van een bekende spammer. Als je denkt dat dit een vergissing is, neem dan contact op met een administrator';
$l['error_stop_forum_spam_fetching'] = 'Sorry, er is iets mis gegaan bij het vergelijken van je ngebruikersnaam en IP adres tegen een spammersdatabase. Hoogstwaarschijnlijk kon de database niet benaderd worden. Probeer het later opnieuw.';
$l['error_suspendedposting'] = 'Je reactie rechten zijn voorlopig opgeschort {1}.<br /><br />

Verloop Datum: {2}';
$l['error_suspendedposting_temporal'] = 'tot {1}';
$l['error_suspendedposting_permanent'] = 'permanent';
