<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Fonta
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 02 Jun 2017 09:22:56 +0000
// --------------------------------------------------------------------------------

$l['nav_newthread'] = 'Nieuw topic plaatsen';
$l['newthread_in'] = 'Nieuw topic in {1}';
$l['post_new_thread'] = 'Nieuw topic plaatsen';
$l['thread_subject'] = 'Onderwerp:';
$l['your_message'] = 'Bericht:';
$l['post_options'] = 'Berichtopties:';
$l['options_sig'] = '<b>Handtekening</b>: hiermee wordt uw handtekening bijgevoegd (alleen voor geregistreerde gebruikers).';
$l['options_emailnotify'] = '<b>E-mailmelding:</b> hiermee ontvangt u een e-mailbericht zodra er een nieuwe reactie is geplaatst (alleen voor geregistreerde gebruikers).';
$l['options_disablesmilies'] = '<b>Emoticons uitschakelen</b>: hiermee voorkomt u dat emoticons in dit bericht worden weergegeven.';
$l['post_thread'] = 'Topic plaatsen';
$l['preview_post'] = 'Voorbeeld weergeven';
$l['poll'] = 'Peiling:';
$l['poll_desc'] = 'U kunt een peiling aan dit topic toevoegen.';
$l['poll_check'] = 'Een peiling aan dit topic toevoegen';
$l['num_options'] = 'Aantal keuzes:';
$l['max_options'] = '(maximaal {1})';
$l['mod_options'] = 'Moderatoropties:';
$l['close_thread'] = '<b>Topic sluiten</b>: hiermee voorkomt u het plaatsen van verdere berichten in dit topic.';
$l['stick_thread'] = '<b>Topic belangrijk maken</b>: hiermee plaatst u dit topic bovenaan in de lijst met topics.';
$l['draft_saved'] = 'Uw topic is als concept opgeslagen.<br />U zult nu naar de lijst met concepten worden gebracht.';
$l['error_post_already_submitted'] = 'U hebt dit topic al geplaatst. Ga naar het forum om uw topic te bekijken.';
$l['no_prefix'] = 'Geen voorvoegsel';
$l['forum_rules'] = '{1} - Regels';
$l['multiquote_external_one'] = 'U hebt &eacute;&eacute;n bericht uit een ander topic geselecteerd.';
$l['multiquote_external'] = 'U hebt {1} berichten uit andere topics geselecteerd.';
$l['multiquote_external_one_deselect'] = 'selectie van dit bericht opheffen';
$l['multiquote_external_deselect'] = 'selectie van alle berichten opheffen';
$l['multiquote_external_one_quote'] = 'Dit bericht ook citeren';
$l['multiquote_external_quote'] = 'Deze berichten ook citeren';
$l['redirect_newthread'] = 'Uw topic is geplaatst.';
$l['redirect_newthread_poll'] = '<br />U zult nu naar de pagina met peilingopties en -instellingen worden gebracht.';
$l['redirect_newthread_moderation'] = '<br />De beheerder heeft aangegeven dat alle nieuwe topics dienen te worden goedgekeurd.<br />U zult nu worden teruggebracht naar de lijst met topics.';
$l['redirect_newthread_thread'] = '<br />U zult nu naar het nieuwe topic worden gebracht.';
$l['invalidthread'] = 'Het opgegeven concept bestaat niet of u hebt niet de rechten om het te mogen bekijken.';
$l['error_stop_forum_spam_spammer'] = 'Sorry, uw {1} matched met dat van een bekende spammer. Als je denkt dat dit een vergissing is, neem dan contact op met een administrator';
$l['error_stop_forum_spam_fetching'] = 'Sorry, er is iets mis gegaan bij het vergelijken van je ngebruikersnaam en IP adres tegen een spammersdatabase. Hoogstwaarschijnlijk kon de database niet benaderd worden. Probeer het later opnieuw.';
$l['error_suspendedposting'] = 'Je reactie rechten zijn voorlopig opgeschort {1}.<br /><br />

Verloop Datum: {2}';
$l['error_suspendedposting_temporal'] = 'tot {1}';
$l['error_suspendedposting_permanent'] = 'permanent';
$l['redirect_newthread_unviewable'] = '<br />U hebt geen rechten op topics te bekijken in dit forum. U wordt nu terug gebracht naar het forum.';
