<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved.
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 12:05:01 +0000
// --------------------------------------------------------------------------------

$l['nav_online'] = 'Wie is er online';
$l['nav_onlinetoday'] = 'Wie was er vandaag online';
$l['viewing_announcements'] = 'Bekijkt aankondigingen in forum <a href="{1}">{2}</a>';
$l['viewing_announcements2'] = 'Bekijkt aankondiging';
$l['viewing_attachment'] = 'Bekijkt bijlage';
$l['viewing_attachment2'] = 'Bekijkt <a href="attachment.php?aid={1}" target="_blank">bijlage</a> in topic <a href="{3}">{2}</a>';
$l['viewing_calendar'] = 'Bekijkt <a href="calendar.php">kalender</a>';
$l['viewing_event'] = 'Bekijkt afspraak';
$l['viewing_event2'] = 'Bekijkt afspraak <a href="{1}">{2}</a>';
$l['adding_event'] = '<a href="calendar.php?action=addevent">Plaatst afspraak</a>';
$l['editing_event'] = 'Bewerkt afspraak';
$l['viewing_contact_us'] = 'Viewing <a href="contact.php">Contact Us</a>';
$l['editing_post'] = 'Bewerkt bericht';
$l['viewing_forum'] = 'Bekijkt forum';
$l['viewing_forum2'] = 'Bekijkt forum <a href="{1}">{2}</a>';
$l['forum_redirect_to'] = 'Wordt doorgestuurd naar <a href="{1}">{2}</a>';
$l['viewing_index'] = '<a href="index.php">Beginpagina</a> {1}';
$l['activating_account'] = 'Activeert account';
$l['viewing_profile'] = 'Bekijkt profiel';
$l['viewing_profile2'] = 'Bekijkt profiel van <a href="{1}">{2}</a>';
$l['registering'] = '<a href="member.php?action=register">Registreert zich</a>';
$l['logging_in'] = '<a href="member.php?action=login">Meldt zich aan</a>';
$l['logging_in_plain'] = 'Meldt zich aan';
$l['logging_out'] = 'Meldt zich af';
$l['emailing_user'] = 'Verstuurt gebruiker een e-mailbericht';
$l['rating_user'] = 'Kent gebruiker een reputatie toe';
$l['viewing_memberlist'] = 'Bekijkt <a href="memberlist.php">ledenlijst</a>';
$l['viewing_whoposted'] = 'Bekijkt wie er een bericht heeft geplaatst';
$l['viewing_whoposted2'] = 'Bekijkt wie er een bericht heeft geplaatst in topic <a href="showthread.php?tid={1}">{2}</a>';
$l['marking_read'] = '<a href="misc.php?action=markread&amp;my_post_key={1}">Markeert alles als gelezen</a>';
$l['viewing_helpdocs'] = 'Bekijkt <a href="misc.php?action=help">help-onderwerpen</a>';
$l['viewing_buddylist'] = 'Bekijkt <a href="misc.php?action=buddypopup">vriendenlijst</a>';
$l['viewing_smilies'] = 'Bekijkt <a href="misc.php?action=smilies">lijst met emoticons</a>';
$l['viewing_syndication'] = 'Bekijkt pagina <a href="misc.php?action=syndication">RSS-syndicatie</a>';
$l['replying_thread'] = 'Plaatst reactie in topic';
$l['replying_thread2'] = 'Plaatst reactie in topic <a href="{1}">{2}</a>';
$l['posting_thread'] = 'Plaatst nieuw topic';
$l['posting_thread2'] = 'Plaatst nieuw topic in <a href="{1}">{2}</a>';
$l['viewing_wol'] = 'Bekijkt <a href="online.php">Wie is er online</a>';
$l['viewing_woltoday'] = 'Bekijkt <a href="online.php?action=today">Wie was er vandaag online</a>';
$l['creating_poll'] = 'Plaatst nieuwe peiling';
$l['editing_poll'] = 'Bewerkt peiling';
$l['viewing_pollresults'] = 'Bekijkt peilingresultaten';
$l['voting_poll'] = 'Stemt op peiling';
$l['using_modtools'] = 'Gebruikt moderatoropties';
$l['sending_pm'] = 'Verstuurt persoonlijk bericht';
$l['reading_pm'] = 'Leest persoonlijk bericht';
$l['editing_pmfolders'] = 'Bewerkt mappen voor persoonlijke berichten';
$l['using_pmsystem'] = 'Gebruikt systeem voor persoonlijke berichten';
$l['reporting_post'] = 'Rapporteert bericht';
$l['searching_forum'] = '<a href="search.php">Doorzoekt</a> {1}';
$l['reading_thread'] = 'Leest topic';
$l['reading_thread2'] = 'Leest topic <a href="{1}">{2}</a> {3}';
$l['viewing_team'] = 'Bekijkt pagina Forumteam';
$l['viewing_stats'] = 'Bekijkt statistieken';
$l['updating_profile'] = '<a href="usercp.php?action=profile">Werkt profiel bij</a>';
$l['updating_options'] = '<a href="usercp.php?action=options">Werkt instellingen bij</a>';
$l['editing_signature'] = '<a href="usercp.php?action=editsig">Bewerkt handtekening</a>';
$l['changing_avatar'] = '<a href="usercp.php?action=avatar">Wijzigt avatar</a>';
$l['viewing_subscriptions'] = 'Bekijkt <a href="usercp.php?action=subscriptions">lijst met geabonneerde topics</a>';
$l['viewing_favorites'] = 'Bekijkt <a href="usercp.php?action=favorites">lijst met favoriete topics</a>';
$l['editing_pad'] = 'Bewerkt inhoud van <a href="usercp.php?action=notepad">persoonlijk kladblok</a>';
$l['editing_password'] = 'Wijzigt <a href="usercp.php?action=password">wachtwoord</a>';
$l['user_cp'] = 'Bekijkt <a href="usercp.php">gebruikersconfiguratiescherm</a>';
$l['viewing_portal'] = 'Bekijkt <a href="portal.php">portaal</a>';
$l['viewing_noperms'] = 'Bekijkt pagina Toestemming geweigerd';
$l['unknown_location'] = '<a href="{1}">Onbekende locatie</a>';
$l['giving_reputation'] = 'Geef reputatie aan <a href="{1}">{2}</a>';
$l['viewing_reputation_report'] = 'Bekijkt <a href="{1}">{2}\'s Reputatie</a>';
$l['viewing_reputation_report2'] = 'Bekijkt Reputatie';
$l['member_resendactivation'] = 'Verstuurt activatie-e-mail opnieuw';
$l['member_lostpw'] = '<a href="member.php?action=lostpw">Herstelt wachtwoord</a>';
$l['sending_thread'] = 'Verstuurt topic naar vriend';
$l['guest'] = 'Gast';
$l['page'] = 'Pagina';
$l['users_online'] = 'Wie is er online';
$l['on_username'] = 'Gebruikersnaam';
$l['time'] = 'Tijd';
$l['location'] = 'Locatie';
$l['online_today'] = 'Wie was er vandaag online';
$l['refresh_page'] = 'Deze pagina vernieuwen';
$l['online_online_plural'] = 'gebruikers';
$l['online_online_singular'] = 'gebruiker';
$l['online_member_plural'] = 'leden';
$l['online_member_singular'] = 'lid';
$l['online_anon_plural'] = 'zijn';
$l['online_anon_singular'] = 'is';
$l['online_guest_plural'] = 'gasten';
$l['online_guest_singular'] = 'gast';
$l['online_count'] = '{1} {2} actief in de afgelopen {3} minuten ({4} {5}, {6} van wie {7} onzichtbaar, en {8} {9}).';
$l['ip'] = 'IP-adres:';
$l['resolves_to'] = 'Hostnaam:';
$l['if_resolvable'] = '(als te herleiden)';
$l['admin_options'] = 'Beheerdersopties:';
$l['search_regip_users'] = 'Zoeken naar gebruikers die zich geregistreerd hebben met dit IP-adres';
$l['search_postip_users'] = 'Zoeken naar gebruikers die berichten geplaatst hebben met dit IP-adres';
$l['lookup'] = '[herleiden]';
$l['member_online_today'] = '<strong>1</strong> lid was vandaag online';
$l['members_were_online_today'] = '<strong>{1}</strong> leden waren vandaag online';
$l['member_online_hidden'] = ' ({1} lid was onzichtbaar)';
$l['members_online_hidden'] = ' ({1} leden waren onzichtbaar)';
$l['rating_thread'] = 'Waardeert topic';
$l['viewing_imcenter'] = 'Bekijkt pagina voor instant messaging';
$l['managing_favorites'] = 'Bekijkt lijst met favoriete topics';
$l['managing_subscriptions'] = 'Bekijkt lijst met geabonneerde topics';
$l['managing_group'] = 'Beheert gebruikersgroep';
$l['viewing_modcp'] = 'Bekijkt moderatorsconfiguratiescherm';
$l['viewing_modlogs'] = 'Bekijkt moderatorslogboek';
$l['managing_announcements'] = 'Beheert aankondigingen';
$l['search_for_user'] = 'Zoekt naar gebruikers';
$l['managing_warninglogs'] = 'Beheert gebruikerslogboek voor waarschuwingen';
$l['searching_ips'] = 'Zoekt naar IP-adres';
$l['viewing_reports'] = 'Bekijkt gerapporteerde berichten';
$l['adding_announcement'] = 'Voegt aankondiging toe';
$l['deleting_announcement'] = 'Verwijdert aankondiging';
$l['editing_announcement'] = 'Bewerkt aankondiging';
$l['managing_modqueue'] = 'Beheert wachtrij voor moderatie';
$l['editing_user_profiles'] = 'Bewerkt gebruiker';
$l['managing_bans'] = 'Beheert verbanningen';
$l['revoking_warning'] = 'Trekt waarschuwing in';
$l['warning_user'] = 'Waarschuwt gebruiker';
$l['viewing_warning'] = 'Bekijkt waarschuwing';
$l['managing_warnings'] = 'Beheert waarschuwingen';
$l['changing_dst'] = 'Wijzigt instellingen voor zomertijd';
$l['printing_thread'] = 'Drukt een topic af';
$l['printing_thread2'] = 'Drukt topic <a href="{1}">{2}</a> af';
$l['managing_buddyignorelist'] = 'Beheert vrienden-/negeerlijst';
