<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 12:06:24 +0000
// --------------------------------------------------------------------------------

$l['nav_postpoll'] = 'Peiling plaatsen';
$l['nav_editpoll'] = 'Peiling bewerken';
$l['nav_pollresults'] = 'Peilingresultaten';
$l['edit_poll'] = 'Peiling bewerken';
$l['delete_poll'] = 'Verwijderen';
$l['delete_q'] = 'Verwijderen?';
$l['delete_note'] = 'Vink het keuzevakje links aan en klik op de knop rechts om deze peiling te verwijderen.';
$l['delete_note2'] = '<b>Opmerking</b>: zodra deze peiling is verwijderd, kunt u deze niet meer terugzetten.';
$l['question'] = 'Vraag/stelling:';
$l['num_options'] = 'Aantal keuzes:';
$l['max_options'] = 'Maximaal';
$l['poll_options'] = 'Keuzes:';
$l['update_options'] = 'Aantal tekstvakken voor keuzes bijwerken';
$l['poll_options_note'] = 'Keuzes dienen kort en krachtig geformuleerd te zijn.';
$l['options'] = 'Opties:';
$l['option_multiple'] = '<b>Meerkeuze toestaan</b>: hiermee geeft u gebruikers de mogelijkheid op meer dan een keuze te stemmen.';
$l['option_multiple_maxoptions'] = 'Maximum aantal opties per lid (0 voor geen limiet):';
$l['option_public'] = '<b>Openbare peiling</b>: hiermee geeft u gebruikers de mogelijkheid te zien waarop andere gebruikers hebben gestemd.';
$l['option_closed'] = '<b>Peiling is gesloten</b>: hiermee kunt u voorkomen dat gebruikers hun stem uitbrengen.';
$l['poll_timeout'] = 'Deadline:';
$l['timeout_note'] = 'Hier kunt u aangeven hoeveel dagen mensen op deze peiling kunnen stemmen. Voer 0 in als deze peiling geen deadline kent.';
$l['days_after'] = 'dagen na';
$l['update_poll'] = 'Peiling bijwerken';
$l['option'] = 'Keuze';
$l['votes'] = 'Aantal stemmen:';
$l['post_new_poll'] = 'Peiling plaatsen';
$l['days'] = 'dagen';
$l['poll_results'] = 'Peilingresultaten';
$l['poll_total'] = 'Totaal aantal stemmen:';
$l['poll_votes'] = 'stem(men)';
$l['redirect_pollposted'] = 'Uw peiling is geplaatst.<br />U zult nu worden teruggebracht naar het topic.';
$l['redirect_pollpostedmoderated'] = 'Uw peiling is geplaatst, maar het topic dient nog te worden goedgekeurd.<br />U zult nu worden teruggebracht naar het forum.';
$l['redirect_pollupdated'] = 'De peiling is bijgewerkt.<br />U zult nu worden teruggebracht naar het topic.';
$l['redirect_votethanks'] = 'Uw stem is uitgebracht.<br />U zult nu worden teruggebracht naar het topic.';
$l['redirect_unvoted'] = 'Uw stem is ongedaan gemaakt.<br />U zult nu worden teruggebracht naar het topic.';
$l['redirect_polldeleted'] = 'De peiling is van dit topic verwijderd.<br />U zult nu worden teruggebracht naar het topic.';
$l['error_polloptiontoolong'] = 'Een of meerdere keuzes die u hebt ingevoerd zijn langer dan de toegestane lengte. Ga terug en kort deze in.';
$l['error_noquestionoptions'] = 'U hebt geen vraag of stelling opgegeven voor deze peiling of u hebt niet genoeg keuzes ingevoerd. Het minimale aantal keuzes voor een peiling is 2. Ga terug en probeer het opnieuw.';
$l['error_pollalready'] = 'Dit topic heeft al een peiling.';
$l['error_nopolloptions'] = 'De gekozen keuze is ongeldig of bestaat niet.';
$l['error_maxpolloptions'] = 'U hebt op te veel opties gestemd. U mag slechts op {1} opties stemmen .<br />Ga alstublieft terug, en probeer het opnieuw.';
$l['error_alreadyvoted'] = 'U hebt uw stem al uitgebracht.';
$l['error_notvoted'] = 'U hebt nog geen stem uitgebracht.';
$l['error_invalidpoll'] = 'De opgegeven peiling is ongeldig of bestaat niet.';
$l['error_pollclosed'] = 'U kunt uw stem niet uitbrengen in een peiling die is gesloten.';
$l['poll_time_limit'] = 'Sorry maar je kan geen peiling toevoegen aan het topic. De administrator heeft ingesteld dat dit alleen kan binnen {1} uur na het posten.';
$l['poll_deleted'] = 'Peiling verwijderd';
$l['poll_edited'] = 'Peiling bewerkt';
$l['error_polloptionsequence'] = 'Een of meerdere peiling opties bevatten karakters die niet gebruikt mogen worden <strong>||~|~||</strong>. Ga aulstublieft terug en haal deze weg';
