<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 12:06:36 +0000
// --------------------------------------------------------------------------------

$l['nav_portal'] = 'Portaal';
$l['posted_by'] = 'Geplaatst door';
$l['forum'] = 'Forum:';
$l['replies'] = 'Reacties';
$l['no_replies'] = 'Geen reacties';
$l['latest_threads'] = 'Meest recente topics';
$l['latest_threads_replies'] = 'Reacties:';
$l['latest_threads_views'] = 'Weergaven:';
$l['latest_threads_lastpost'] = 'Laatste bericht door';
$l['private_messages'] = 'Persoonlijke berichten';
$l['pms_received_new'] = '{1}, u heeft <b>{2}</b> ongelezen bericht(en).';
$l['pms_unread'] = 'ongelezen berichten';
$l['pms_total'] = 'berichten in totaal';
$l['search_forums'] = 'Forums doorzoeken';
$l['advanced_search'] = 'Geavanceerd zoeken';
$l['forum_stats'] = 'Statistieken';
$l['num_members'] = 'Leden:';
$l['latest_member'] = 'Meest recente lid:';
$l['num_threads'] = 'Aantal topics:';
$l['num_posts'] = 'Aantal berichten:';
$l['full_stats'] = 'Volledige statistieken';
$l['welcome'] = 'Welkom, {1}';
$l['guest'] = 'gast';
$l['guest_welcome_registration'] = 'U dient zich te <a href="{1}">registreren</a> voordat u berichten kunt plaatsen op dit forum.';
$l['username'] = 'Gebruikersnaam';
$l['password'] = 'Wachtwoord';
$l['login'] = 'Aanmelden';
$l['member_welcome_lastvisit'] = 'Laatste bezoek:';
$l['since_then'] = 'Sindsdien zijn er:';
$l['new_announcements'] = '{1} nieuwe aankondigingen';
$l['new_announcement'] = 'E&eacute;n nieuwe aankondiging';
$l['new_threads'] = '{1} nieuwe topics';
$l['new_thread'] = 'E&eacute;n nieuw topic';
$l['new_posts'] = '{1} nieuwe berichten';
$l['new_post'] = 'E&eacute;n nieuw bericht';
$l['view_new'] = 'Nieuwe berichten';
$l['view_todays'] = 'Berichten van vandaag';
$l['online'] = 'Gebruikers online';
$l['online_user'] = 'Er is momenteel <b>1</b> gebruiker online.';
$l['online_users'] = 'Er zijn momenteel <b>{1}</b> gebruikers online.';
$l['online_counts'] = '<b>{1}</b> leden | <b>{2}</b> gasten';
$l['print_this_item'] = 'Dit onderdeel afdrukken';
$l['send_to_friend'] = 'Dit onderdeel naar een vriend sturen';
$l['latest_announcements'] = 'Laatste Aankondigingen';
$l['portal_disabled'] = 'Je kan het portaal niet gebruiken omdat deze is uitgeschakeld door een administrator.';
