<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 12:07:31 +0000
// --------------------------------------------------------------------------------

$l['redirect_threadrated'] = 'Het topic is gewaardeerd.<br />U zult nu worden teruggebracht naar het topic.';
$l['error_invalidrating'] = 'U hebt een ongeldige waardering voor dit topic gekozen. Ga terug en probeer het opnieuw.';
$l['error_alreadyratedthread'] = 'U hebt dit topic al gewaardeerd.';
$l['error_cannotrateownthread'] = 'Sorry, u kan uw eigen topic niet waarderen.';
$l['rating_votes_average'] = '{1} stem - {2} van 5 gemiddeld';
$l['one_star'] = '1 ster';
$l['two_stars'] = '2 sterren';
$l['three_stars'] = '3 sterren';
$l['four_stars'] = '4 sterren';
$l['five_stars'] = '5 sterren';
$l['rating_added'] = 'Uw waardering is toegevoegd.';
