<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved.
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 12:07:43 +0000
// --------------------------------------------------------------------------------

$l['report_reason'] = 'Rapporteer reden:';
$l['report_to_mod'] = 'Dit bericht aan een moderator rapporteren';
$l['close_window'] = 'Venster sluiten';
$l['report_content'] = 'Rapporteer Content';
$l['report_reason_post'] = 'Rapporteer Bericht';
$l['report_reason_profile'] = 'Rapporteer Profiel';
$l['report_reason_reputation'] = 'Rapporteer Reputatie';
$l['report_reason_bad'] = 'Ongepaste Content';
$l['report_reason_spam'] = 'Spam';
$l['report_reason_rules'] = 'Breekt forum regels';
$l['report_reason_wrong'] = 'Verkeerde Forum';
$l['report_reason_other'] = 'Anders';
$l['success_report_voted'] = 'Bedankt voor het rapporteren van deze content.<br />Een moderator zal hier spoedig naar kijken.';
$l['error_report_length'] = 'Geef alstublief een gedetaileerde reden waarom u deze content rapporteerd.';
$l['error_invalid_report'] = 'Deze content bestaat niet of kan niet worden gerapporteerd.';
$l['error_report_duplicate'] = 'Deze content is reeds door een andere gebruiker gerapporteerd.<br />Je kunt de content hieronder ook rapporteren.';
$l['report_reason_other_description'] = 'Indien \'Anders\' is gekozen, dient u een reden op te geven.';
