<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Fonta
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 18*
// Last edited in MyBB Editor by : Fonta
// Last edited date : Mon, 27 Jul 2020 10:25:07 +0000
// --------------------------------------------------------------------------------

$l['report_reason'] = 'Rapporteer reden:';
$l['report_to_mod'] = 'Dit bericht aan een moderator rapporteren';
$l['close_window'] = 'Venster sluiten';
$l['report_content'] = 'Rapporteer Content';
$l['report_reason_post'] = 'Rapporteer Bericht';
$l['report_reason_profile'] = 'Rapporteer Profiel';
$l['report_reason_reputation'] = 'Rapporteer Reputatie';
$l['report_reason_bad'] = 'Ongepaste Content';
$l['report_reason_spam'] = 'Spam';
$l['report_reason_rules'] = 'Breekt forum regels';
$l['report_reason_wrong'] = 'Verkeerde Forum';
$l['report_reason_other'] = 'Anders';
$l['success_report_voted'] = 'Bedankt voor het rapporteren van deze content.<br />Een moderator zal hier spoedig naar kijken.';
$l['error_report_length'] = 'Geef alstublief een gedetaileerde reden waarom u deze content rapporteerd.';
$l['error_invalid_report'] = 'Deze {1} bestaat niet of kan niet worden gerapporteerd.';
$l['error_report_duplicate'] = 'Deze content is reeds door een andere gebruiker gerapporteerd.<br />U kunt de content hieronder ook rapporteren.';
$l['report_reason_other_description'] = 'Geef alstublieft meer informatie waarom u deze content wilt rapporteren.';
$l['error_invalid_report_reason'] = 'De geselecteerde reden is foutief.';
$l['error_comment_required'] = 'Voor de geselecteerde reden is een aanvulling nodig.';
