<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 12:09:12 +0000
// --------------------------------------------------------------------------------

$l['nav_search'] = 'Zoeken';
$l['nav_results'] = 'Zoekresultaten';
$l['pages_last'] = 'laatste';
$l['search'] = 'Zoeken';
$l['search_keyword'] = 'Zoeken op trefwoord';
$l['search_username'] = 'Zoeken op gebruikersnaam';
$l['search_entire_post'] = 'Gehele berichten doorzoeken';
$l['search_titles_only'] = 'Alleen titels doorzoeken';
$l['match_username'] = 'Identieke gebruikersnaam';
$l['search_forums'] = 'Zoeken in forum(s)';
$l['search_all_forums'] = 'Alle forums doorzoeken';
$l['search_options'] = 'Zoekmogelijkheden';
$l['threads_at_least'] = 'Topics zoeken met ten minste';
$l['threads_at_most'] = 'Topics zoeken met ten meeste';
$l['find_anydate'] = 'Berichten zoeken van elke datum';
$l['find_yesterday'] = 'Berichten zoeken van gisteren';
$l['find_lastweek'] = 'Berichten zoeken van vorige week';
$l['find_2weeks'] = 'Berichten zoeken van 2 weken geleden';
$l['find_month'] = 'Berichten zoeken van 1 maand geleden';
$l['find_3months'] = 'Berichten zoeken van 3 maanden geleden';
$l['find_6months'] = 'Berichten zoeken van 4 maanden geleden';
$l['find_year'] = 'Berichten zoeken van een jaar geleden';
$l['and_newer'] = 'en nieuwer';
$l['and_older'] = 'en ouder';
$l['sorting_options'] = 'Sorteermogelijkheden';
$l['sort_lastpost'] = 'Resultaten sorteren op datum van laatste bericht';
$l['sort_author'] = 'Resultaten sorteren op auteur';
$l['sort_forum'] = 'Resultaten sorteren op forum';
$l['sort_in'] = 'in';
$l['sort_asc'] = 'oplopende';
$l['sort_desc'] = 'aflopende';
$l['sort_order'] = 'volgorde';
$l['asc'] = 'opl';
$l['desc'] = 'afl';
$l['display_options'] = 'Weergave-instellingen';
$l['show_results_as'] = 'Resultaten weergeven als';
$l['show_results_threads'] = 'topics';
$l['show_results_posts'] = 'berichten';
$l['search_results'] = 'Zoekresultaten';
$l['post'] = 'Bericht';
$l['author'] = 'Auteur';
$l['forum'] = 'Forum';
$l['replies'] = 'Reacties';
$l['views'] = 'Weergaven';
$l['posted'] = 'Geplaatst op';
$l['thread'] = 'Topic';
$l['lastpost'] = 'Laatste bericht';
$l['post_thread'] = 'Topic:';
$l['post_subject'] = 'Bericht:';
$l['replies2'] = 'reacties';
$l['selectall'] = 'Alle bijkomende resultaten selecteren?';
$l['any_prefix'] = 'Topics zoeken met elk voorvoegsel';
$l['no_prefix'] = 'Geen voorvoegsel';
$l['inline_thread_moderation'] = 'topicmoderatie:';
$l['close_threads'] = 'Sluiten';
$l['open_threads'] = 'Openen';
$l['stick_threads'] = 'Belangrijk maken';
$l['unstick_threads'] = 'Onbelangrijk maken';
$l['delete_threads'] = 'Verwijderen';
$l['move_threads'] = 'Verplaatsen';
$l['approve_threads'] = 'Goedkeuren';
$l['unapprove_threads'] = 'Afkeuren';
$l['inline_soft_delete_posts'] = 'Tijdelijk Verwijderen Berichten';
$l['inline_restore_posts'] = 'Herstel Berichten';
$l['inline_delete_posts'] = 'Berichten permanent verwijdern';
$l['inline_merge_posts'] = 'Samenvoegen';
$l['inline_split_posts'] = 'Splitsen';
$l['inline_approve_posts'] = 'Goedkeuren';
$l['inline_unapprove_posts'] = 'Afkeuren';
$l['inline_post_moderation'] = 'Directe berichtmoderatie:';
$l['inline_go'] = 'Uitvoeren';
$l['clear'] = 'Selectie opheffen';
$l['icon_dot'] = 'Bevat berichten van u. ';
$l['icon_no_new'] = 'Bevat geen nieuwe berichten.';
$l['icon_new'] = 'Bevat nieuwe berichten.';
$l['icon_hot'] = ' Populair topic (recent).';
$l['icon_lock'] = ' Topic is gesloten.';
$l['attachment_count'] = 'Dit topic bevat &eacute;&eacute;n bijlage';
$l['attachment_count_multiple'] = 'Dit topic bevat {1} bijlagen';
$l['goto_first_unread'] = 'Naar eerste ongelezen bericht gaan';
$l['page_selected'] = 'Alle <strong>{1}</strong> resultaten op deze pagina zijn geselecteerd.';
$l['all_selected'] = 'Alle <strong>{1}</strong> resultaten in deze zoekopdracht zijn geselecteerd.';
$l['select_all'] = 'Alle <strong>{1}</strong> resultaten in deze zoekopdracht selecteren.';
$l['clear_selection'] = 'Selectie ongedaan maken';
$l['search_user'] = 'Zoek naar een gebruiker';
$l['results'] = 'resultaten';
$l['mod_options'] = 'Moderatoropties';
$l['find_all'] = 'Alles zoeken';
$l['find_only_approved'] = '';
$l['find_only_unapproved'] = '';
$l['find_only_softdeleted'] = '';
$l['redirect_searchresults'] = 'Uw zoekopdracht is verstuurd.<br />U zult nu naar de lijst met resultaten worden gebracht.';
$l['error_minsearchlength'] = 'Een of meerdere van uw zoektermen zijn te kort. De minimale lengte voor zoektermen is {1} tekens.<br /><br />als u wilt zoeken naar een combinatie van woorden, plaats deze combinatie dan tussen dubbele aanhalingstekens. Voorbeeld: "Pa\\\'s wijze lynx bezag vroom het fikse aquaduct".';
$l['error_nosearchresults'] = 'Er zijn geen resultaten gevonden voor de zoekopdracht die u uitvoerde. Maak een nieuwe zoekopdracht en probeer het opnieuw.';
$l['error_no_search_support'] = 'Deze database ondersteunt geen zoekopdrachten.';
$l['error_nosearchterms'] = 'U hebt geen geldige zoekopdracht opgegeven. Ga terug en verfijn uw zoekopdracht of geef zoekwoorden op.';
$l['error_searchflooding_1'] = 'U kunt slechts &eacute;&eacute;n zoekopdracht per {1} seconden uitvoeren. Wacht nog &eacute;&eacute;n seconde en probeer het opnieuw.';
$l['error_searchflooding'] = 'U kunt slechts &eacute;&eacute;n zoekopdracht per {1} seconden uitvoeren. Wacht {2} seconden en probeer het opnieuw.';
$l['error_invalidsearch'] = 'Uw zoekopdracht was ongeldig. Ga terug en probeer het opnieuw.';
$l['display_all'] = 'Alles zoeken';
$l['display_only_approved'] = 'Alleen goedgekeurde berichten zoeken';
$l['display_only_unapproved'] = 'Alleen afgekeurde berichten zoeken';
$l['display_only_softdeleted'] = 'Alleen voorlopig verwijderde berichten zoeken';
$l['soft_delete_threads'] = 'Topics voorlopig verwijderen';
$l['restore_threads'] = 'Topics herstellen';
$l['inline_move_posts'] = 'Berichten verplaatsen';
