<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 12:09:43 +0000
// --------------------------------------------------------------------------------

$l['nav_sendthread'] = 'Topic aan vriend laten zien';
$l['send_thread'] = 'Topic aan vriend laten zien';
$l['recipient'] = 'Aan:';
$l['recipient_note'] = 'Voer hier het e-mailadres van uw vriend in.';
$l['subject'] = 'Onderwerp:';
$l['message'] = 'Bericht:';
$l['image_verification'] = '';
$l['verification_subnote'] = '';
$l['verification_note'] = '';
$l['error_nosubject'] = 'U moet een onderwerp invoeren.';
$l['error_nomessage'] = 'U moet een bericht invoeren.';
