<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Fonta
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 18*
// Last edited in MyBB Editor by : Fonta
// Last edited date : Mon, 27 Jul 2020 10:56:36 +0000
// --------------------------------------------------------------------------------

$l['delete_poll'] = 'Peiling verwijderen';
$l['close_thread'] = 'Topic sluiten';
$l['stick_thread'] = 'Belangrijk topic';
$l['author'] = 'Auteur';
$l['message'] = 'Bericht';
$l['threaded'] = 'Geneste weergave';
$l['linear'] = 'Lineaire weergave';
$l['thread_modes'] = 'Topic Modes';
$l['next_oldest'] = 'Ouder topic';
$l['next_newest'] = 'Nieuwer topic';
$l['view_printable'] = 'Afdrukversie weergeven';
$l['send_thread'] = 'Topic aan vriend laten zien';
$l['subscribe_thread'] = 'Op topic abonneren';
$l['unsubscribe_thread'] = 'Abonnement opzeggen';
$l['add_poll_to_thread'] = 'Voeg peiling toe aan dit topic';
$l['moderation_options'] = 'Moderatoropties:';
$l['delayed_moderation'] = 'Uitgestelde moderatie';
$l['thread_notes'] = 'Opmerkingen/logboek weergeven';
$l['open_close_thread'] = 'Topic openen/sluiten';
$l['approve_thread'] = 'Topic goedkeuren';
$l['unapprove_thread'] = 'Topic afkeuren';
$l['soft_delete_thread'] = 'Topic voorlopig verwijderen';
$l['restore_thread'] = 'Herstel Topic';
$l['delete_thread'] = 'Topic definitief verwijderen';
$l['delete_posts'] = 'Berichten verwijderen';
$l['move_thread'] = 'Topic verplaatsen/kopi&euml;ren';
$l['stick_unstick_thread'] = 'Topic (on)belangrijk maken';
$l['split_thread'] = 'Topic splitsen';
$l['merge_threads'] = 'Topics samenvoegen';
$l['remove_redirects'] = 'Koppelingen verwijderen';
$l['remove_subscriptions'] = 'Alle abonnementen opzeggen';
$l['poll'] = 'Peiling:';
$l['show_results'] = 'Resultaten weergeven';
$l['edit_poll'] = 'Peiling bewerken';
$l['public_note'] = '<b>Opmerking</b>: dit is een openbare peiling; andere gebruikers kunnen zien waarop u hebt gestemd.';
$l['total'] = 'Totaal aantal stemmen:';
$l['vote'] = 'Uw stem uitbrengen';
$l['total_votes'] = '{1}';
$l['you_voted'] = '* U hebt op deze optie gestemd.';
$l['poll_closed'] = 'Deze peiling is gesloten.';
$l['poll_closes'] = 'Deze peiling sluit op: {1}';
$l['already_voted'] = 'U hebt al op deze peiling gestemd.';
$l['undo_vote'] = 'Stem ongedaan maken';
$l['quick_reply'] = 'Snel reactie plaatsen';
$l['message_note'] = 'Typ hier uw reactie op dit topic.';
$l['signature'] = 'Handtekening';
$l['email_notify'] = 'E-mailmelding';
$l['disable_smilies'] = 'Emoticons uitschakelen';
$l['post_reply'] = 'Reactie plaatsen';
$l['post_reply_img'] = 'Reactie plaatsen';
$l['new_reply'] = 'Nieuwe Reactie';
$l['search_button'] = 'Zoeken';
$l['post_thread'] = 'Nieuw topic plaatsen';
$l['preview_post'] = 'Voorbeeld weergeven';
$l['rating_average'] = '{1} stemmen - gemiddelde waardering is {2}';
$l['rate_thread'] = 'Topic waarderen:';
$l['thread_rating'] = 'Waardering:';
$l['similar_threads'] = 'Lijst met mogelijk verwante topics';
$l['thread'] = 'Topic';
$l['replies'] = 'Reacties';
$l['views'] = 'Weergaven';
$l['lastpost'] = 'Laatste bericht';
$l['messages_in_thread'] = 'Berichten in dit topic';
$l['users_browsing_thread'] = 'Gebruikers die dit topic lezen:';
$l['users_browsing_thread_guests'] = '{1} gast(en)';
$l['users_browsing_thread_invis'] = '{1} onzichtbare gebruiker(s)';
$l['users_browsing_thread_reading'] = 'Bezig met lezen...';
$l['inline_soft_delete_posts'] = 'Bericht voorlopig verwijderen';
$l['inline_restore_posts'] = 'Herstel Berichten';
$l['inline_delete_posts'] = 'Definitief Verwijderen';
$l['inline_merge_posts'] = 'Samenvoegen';
$l['inline_split_posts'] = 'Splitsen';
$l['inline_move_posts'] = 'Berichten Verplaatsen';
$l['inline_approve_posts'] = 'Berichten Goedkeuren';
$l['inline_unapprove_posts'] = 'Berichten Afkeuren';
$l['inline_post_moderation'] = 'Directe berichtmoderatie: ';
$l['inline_go'] = 'Uitvoeren';
$l['clear'] = 'Selectie opheffen';
$l['thread_closed'] = 'Topic is gesloten';
$l['no_subject'] = 'Geen onderwerp';
$l['error_nonextnewest'] = 'Er zijn geen topics die nieuwer zijn dan het topic die u nu bekijkt.';
$l['error_nonextoldest'] = 'Er zijn geen topics die ouder zijn dan het topic die u nu bekijkt.';
$l['quickreply_multiquote_selected'] = 'U hebt &eacute;&eacute;n of meerdere berichten geselecteerd om te citeren.';
$l['quickreply_multiquote_now'] = 'Deze berichten nu citeren';
$l['or'] = 'of';
$l['quickreply_multiquote_deselect'] = 'de selectie opheffen';
$l['search_thread'] = 'Topic doorzoeken';
$l['enter_keywords'] = 'Voer zoektermen in';
$l['view_thread_notes'] = 'Topic Notities';
$l['view_all_notes'] = 'Bekijk Alle Notities';
$l['save_changes'] = 'Wijzigingen Opslaan';
$l['cancel_edit'] = 'Bewerken Annuleren';
$l['quick_edit_update_error'] = 'Er is een fout opgetreden tijdens het bewerken van je bericht:';
$l['quick_reply_post_error'] = 'Er is een fout opgetreden tijdens het plaatsen van je bericht:';
$l['quick_delete_error'] = 'Er is een fout opgetreden tijdens het verwijderen van je bericht:';
$l['quick_delete_success'] = 'Het bericht is succesvol verwijderd.';
$l['quick_delete_thread_success'] = 'Het topic is succesvol verwijderd.';
$l['quick_restore_error'] = 'Er is een fout opgetreden tijdens het herstellen van je bericht:';
$l['quick_restore_success'] = 'Het bericht is succesvol hersteld.';
$l['no_voting_permission'] = 'U heeft geen rechten om te stemmen in deze poll.';
$l['post_deleted_error'] = 'Je kan deze actie niet uitvoeren op een verwijderd bericht.';
