<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved.
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 12:09:57 +0000
// --------------------------------------------------------------------------------

$l['nav_showteam'] = 'Forumteam';
$l['forum_team'] = 'Forumteam';
$l['moderators'] = 'Moderators';
$l['username'] = 'Gebruikersnaam';
$l['lastvisit'] = 'Last Visit';
$l['email'] = 'E-mail';
$l['pm'] = 'PB';
$l['mod_forums'] = 'Forum(s)';
$l['online'] = 'Online';
$l['offline'] = 'Offline';
$l['group_leaders'] = 'Groepsleiders';
$l['group_members'] = 'Groepsleden';
$l['no_members'] = 'Er bevinden zich geen leden in deze groep.';
$l['error_noteamstoshow'] = 'Er zijn geen teamleden die kunnen worden weergegeven.';
$l['away'] = 'Afwezig';
