<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Fonta
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 18*
// Last edited in MyBB Editor by : Fonta
// Last edited date : Mon, 27 Jul 2020 10:55:37 +0000
// --------------------------------------------------------------------------------

$l['nav_showteam'] = 'Forumteam';
$l['forum_team'] = 'Forumteam';
$l['moderators'] = 'Moderators';
$l['username'] = 'Gebruikersnaam';
$l['lastvisit'] = 'Last Visit';
$l['email'] = 'E-mail';
$l['pm'] = 'PB';
$l['mod_forums'] = 'Forum(s)';
$l['online'] = 'Online';
$l['offline'] = 'Offline';
$l['group_leaders'] = 'Groepsleiders';
$l['group_members'] = 'Groepsleden';
$l['no_members'] = 'Er bevinden zich geen leden in deze groep.';
$l['error_noteamstoshow'] = 'Er zijn geen teamleden die kunnen worden weergegeven.';
$l['away'] = 'Afwezig';
$l['mod_groups'] = 'Groep(en)';
$l['showteam_disabled'] = 'Het weergeven van het forum team is uitgeschakeld door de administrator.';
