<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved.
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 12:10:07 +0000
// --------------------------------------------------------------------------------

$l['nav_stats'] = 'Forum Statistieken';
$l['stats_disabled'] = 'U kunt de statistieken pagina niet bekijken omdat deze is uitgeschakeld door een administrator.';
$l['board_stats'] = 'Forum Statistieken';
$l['none'] = 'Geen';
$l['totals'] = 'Totalen';
$l['averages'] = 'Gemiddelden';
$l['posts'] = 'Berichten:';
$l['threads'] = 'Topics:';
$l['members'] = 'Leden:';
$l['ppd'] = 'Berichten per dag:';
$l['tpd'] = 'Topics per dag:';
$l['mpd'] = 'Leden per dag:';
$l['ppm'] = 'Berichten per lid:';
$l['tpm'] = 'Topics per lid:';
$l['rpt'] = 'Berichten per topic:';
$l['no_posts'] = 'Nee';
$l['general'] = 'Algemeen';
$l['newest_member'] = 'Nieuwste Lid:';
$l['members_posted'] = 'Leden die hebben gereageerd:';
$l['todays_top_poster'] = 'meeste reactie vandaag door: <b>{1}</b> (<b>{2}</b> berichten)';
$l['popular_forum'] = 'Meest populaire forum: <b>{1}</b> (<b>{2}</b> berichten, <b>{3}</b> topics)';
$l['most_popular'] = 'Meest Populair...';
$l['most_replied_threads'] = 'Meest actieve topics';
$l['most_viewed_threads'] = 'Meesty bekeken topics';
$l['not_enough_info_stats'] = 'Sorry, but there is not enough information on this board to generate statistics. Before statistics can be generated this board needs to contain at least 1 member and 1 thread.';
$l['replies'] = 'antwoorden';
$l['views'] = 'weergaven';
$l['top_referrer'] = 'Top referrer: <strong>{1}</strong> (<strong>{2}</strong> referrals)';
