<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Fonta
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 12:27:39 +0000
// --------------------------------------------------------------------------------

$l['all_forums'] = 'Alle forums';
$l['forum'] = 'Forum:';
$l['posted_by'] = 'Geplaatst door';
$l['on'] = 'op';
$l['portal'] = 'Portaal';
