<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 12:12:56 +0000
// --------------------------------------------------------------------------------

$l['ucp_nav_width'] = '197';
$l['ucp_nav_menu'] = 'Menu';
$l['ucp_nav_messenger'] = 'Persoonlijke berichten';
$l['ucp_nav_compose'] = 'Bericht opstellen';
$l['ucp_nav_tracking'] = 'Berichten opsporen';
$l['ucp_nav_edit_folders'] = 'Mappen beheren';
$l['ucp_nav_profile'] = 'Uw profiel';
$l['ucp_nav_edit_profile'] = 'Profiel bewerken';
$l['ucp_nav_edit_options'] = 'Instellingen wijzigen';
$l['ucp_nav_change_email'] = 'E-mailadres wijzigen';
$l['ucp_nav_change_pass'] = 'Wachtwoord wijzigen';
$l['ucp_nav_change_username'] = 'Gebruikersnaam wijzigen';
$l['ucp_nav_edit_sig'] = 'Handtekening bewerken';
$l['ucp_nav_change_avatar'] = 'Avatar wijzigen';
$l['ucp_nav_misc'] = 'Diversen';
$l['ucp_nav_editlists'] = 'Buddy- en negeerlijst';
$l['ucp_nav_favorite_threads'] = 'Favoriete topics';
$l['ucp_nav_subscribed_threads'] = 'Geabonneerde topics';
$l['ucp_nav_forum_subscriptions'] = 'Geabonneerde forums';
$l['ucp_nav_drafts'] = 'Opgeslagen concepten';
$l['ucp_nav_drafts_active'] = '<strong>Opgeslagen concepten ({1})</strong>';
$l['ucp_nav_notepad'] = 'Persoonlijk kladblok';
$l['ucp_nav_view_profile'] = 'Profiel weergeven';
$l['ucp_nav_home'] = 'Begin GebruikersCS';
$l['ucp_nav_usergroups'] = 'Groepen beheren';
$l['ucp_nav_attachments'] = 'Bijlagen beheren';
