<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved.
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 12:13:09 +0000
// --------------------------------------------------------------------------------

$l['nav_profile'] = 'Profiel van {1}';
$l['nav_warning_log'] = 'Gebruikerslogboek voor waarschuwingen';
$l['nav_add_warning'] = 'Gebruiker waarschuwen';
$l['nav_view_warning'] = 'Details';
$l['warning_for_post'] = 'Bericht:';
$l['already_expired'] = 'Verlopen';
$l['details_username'] = 'Gebruikersnaam';
$l['warning_active'] = 'Actief';
$l['warning_revoked'] = 'Ingetrokken';
$l['warning_log'] = 'Gebruikerslogboek voor waarschuwingen';
$l['warning'] = 'Waarschuwing';
$l['issued_by'] = 'Uitgedeeld door';
$l['date_issued'] = 'Gewaarschuwd op';
$l['expiry_date'] = 'Verloopt';
$l['active_warnings'] = 'Actieve waarschuwingen';
$l['expired_warnings'] = 'Verlopen waarschuwingen';
$l['warning_points'] = '({1} waarschuwingspunten)';
$l['no_warnings'] = 'Deze gebruiker heeft nog geen waarschuwingen gehad of alle waarschuwingen zijn verwijderd.';
$l['warn_user'] = 'Gebruiker waarschuwen';
$l['post'] = 'Bericht:';
$l['warning_note'] = 'Beheerdersnotities:';
$l['details_warning_note'] = 'Beheerdersnotities';
$l['warning_type'] = 'Waarschuwing:';
$l['custom'] = 'Eigen reden';
$l['reason'] = 'Reden:';
$l['points'] = 'Punten:';
$l['details_reason'] = 'Reason';
$l['warn_user_desc'] = 'U kunt hier het waarschuwingsniveau van deze gebruiker verhogen als hij of zij een of meerdere regels heeft overtreden.';
$l['send_pm'] = 'Gebruiker informeren:';
$l['send_user_warning_pm'] = 'Deze gebruiker een persoonlijk bericht sturen ter informatie';
$l['send_pm_subject'] = 'Onderwerp:';
$l['warning_pm_subject'] = 'U bent gewaarschuwd';
$l['send_pm_message'] = 'Bericht:';
$l['warning_pm_message'] = 'Beste {1},

Het personeel van {2} heeft u gewaarschuwd.
--

--';
$l['send_pm_options'] = 'Options:';
$l['send_pm_options_anonymous'] = '<strong>Anonymous PM</strong>: send this private message as an anonymous user.';
$l['expiration_never'] = 'permanent';
$l['expiration_hours'] = 'uur';
$l['expiration_days'] = 'dagen';
$l['expiration_weeks'] = 'weken';
$l['expiration_months'] = 'maanden';
$l['redirect_warned_banned'] = 'De gebruiker is {2} naar de verbannen groep {1} verplaatst.';
$l['redirect_warned_suspended'] = 'De gebruiker is {1} het recht om berichten te plaatsen ontnomen.';
$l['redirect_warned_moderate'] = 'Berichten van deze gebruiker moeten {1} worden goedgekeurd voordat ze zichtbaar zijn.';
$l['redirect_warned_pmerror'] = '<br /><br />Please note that the PM was not sent.';
$l['redirect_warned'] = 'Het waarschuwingsniveau van {1} is verhoogd naar {2}%.{3}<br /><br />U zult nu worden teruggebracht naar waar u vandaan kwam.';
$l['error_warning_system_disabled'] = 'Het waarschuwingssysteem is uitgeschakeld door een beheerder.';
$l['error_cant_warn_group'] = 'U mag gebruikers in deze gebruikergroep niet waarschuwen.';
$l['error_invalid_user'] = 'U hebt een ongeldige gebruiker opgegeven.';
$l['details'] = 'Details';
$l['view'] = 'Bekijken';
$l['current_warning_level'] = 'Huidige waarschuwingsniveau: <strong>{1}%</strong> ({2}/{3})';
$l['warning_details'] = 'Details';
$l['revoke_warning'] = 'Waarschuwing intrekken';
$l['revoke_warning_desc'] = 'Als u deze waarschuwing wilt intrekken, voer dan hieronder een reden daarvoor in. Het intrekken van een waarschuwing heeft geen gevolgen voor maatregelen die zijn opgelegd als de gebruiker door deze waarschuwing een waarschuwingsniveau overschreed.';
$l['warning_is_revoked'] = 'Deze waarschuwing is ingetrokken';
$l['revoked_by'] = 'Ingetrokken door:';
$l['date_revoked'] = 'Ingetrokken op:';
$l['warning_already_revoked'] = 'Deze waarschuwing is al ingetrokken.';
$l['no_revoke_reason'] = 'U hebt geen reden ingevoerd voor het intrekken van deze waarschuwing.';
$l['redirect_warning_revoked'] = 'Deze waarschuwing is ingetrokken en het aantal waarschuwingspunten van de gebruiker is verminderd.';
$l['result'] = 'Resultaat:';
$l['result_banned'] = 'De gebruiker zal {2} naar de verbannen groep {1} worden verplaatst.';
$l['result_suspended'] = 'De gebruiker zal {1} het recht om berichten te plaatsen worden ontnomen.';
$l['result_moderated'] = 'Berichten van deze gebruiker zullen {1} worden goedgekeurd voordat ze zichtbaar zijn.';
$l['result_period'] = 'voor {1} {2}';
$l['result_period_perm'] = 'permanent';
$l['hour_or_hours'] = 'uur';
$l['day_or_days'] = 'dagen';
$l['week_or_weeks'] = 'weken';
$l['month_or_months'] = 'maanden';
$l['expires'] = 'Verloopt op:';
$l['new_warning_level'] = 'Nieuw waarschuwingsniveau:';
$l['error_cant_warn_user'] = 'U mag deze gebruiker niet waarschuwen.';
$l['existing_post_warnings'] = 'Gegeven waarschuwingen voor dit bericht';
