<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved.
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Gianni Fontanini (Fonta)
// Language pack translators website : https://www.bug-community.com
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Fonta
// Last edited date : Fri, 22 Jan 2016 12:13:47 +0000
// --------------------------------------------------------------------------------

$l['no_new_subject'] = 'U hebt geen nieuw onderwerp ingevoerd.';
$l['post_moderation'] = 'Uw bericht is in afwachting van een moderator.';
$l['thread_moderation'] = 'Uw topic is in afwachting van een moderator.';
$l['post_doesnt_exist'] = 'Het opgegeven bericht bestaat niet.';
$l['thread_doesnt_exist'] = 'Het opgegeven topic bestaat niet.';
$l['thread_closed_edit_subjects'] = 'U kunt geen onderwerpen bewerken in dit topic, omdat dit topic is gesloten.';
$l['no_permission_edit_subject'] = 'U hebt geen toestemming om het onderwerp van dit topic te bewerken.';
$l['thread_closed_edit_message'] = 'U kunt geen berichten bewerken in dit topic, omdat dit topic is gesloten.';
$l['no_permission_edit_post'] = 'U hebt geen toestemming om dit bericht te bewerken.';
$l['edit_time_limit'] = 'U kunt berichten alleen bewerken binnen {1} minuten nadat zij geplaatst zijn.';
$l['postbit_edited'] = 'Dit bericht is voor het laatst bewerkt op {1} door';
$l['postbit_editreason'] = 'Bewerk Reden';
$l['save_changes'] = 'Bericht bijwerken';
$l['cancel_edit'] = 'Annuleren';
$l['answer_valid_not_exists'] = 'De vraag die u beantwoord bestaat niet.';
$l['captcha_not_exists'] = 'De afbeelding met verificatiecode die u probeert te vernieuwen, bestaat niet.';
$l['captcha_valid_not_exists'] = 'De afbeelding met verificatiecode die u probeert te bekijken, bestaat niet.';
$l['captcha_does_not_match'] = 'U hebt een onjuiste verificatiecode ingevoerd. Voer de code precies zo in als hij in de afbeelding staat.';
$l['captcha_matches'] = 'U hebt de juiste verificatiecode ingevoerd.';
$l['answer_does_not_match'] = 'Het door u gegeven antwoord is onjuist.';
$l['banned_username'] = 'Deze gebruikersnaam is verboden door een beheerder.';
$l['banned_characters_username'] = 'Deze gebruikersnaam bevat een of meerdere tekens die niet zijn toegestaan.';
$l['complex_password_fails'] = 'Het wachtwoord vereist een hoofdletter, kleine letter en een cijfer.';
$l['username_taken'] = 'De gebruikersnaam {1} is al in gebruik.';
$l['username_available'] = 'De gebruikersnaam {1} is beschikbaar.';
$l['invalid_username'] = 'De gebruikersnaam {1} is niet in gebruik.';
$l['valid_username'] = 'De gebruikersnaam {1} is een geldige doorverwijzer.';
$l['buddylist_error'] = 'Het lijkt erop dat u geen vrienden in uw vriendenlijst hebt. U moet vrienden toevoegen voordat u deze functie kunt gebruiken.';
$l['close'] = 'Sluiten';
$l['select_buddies'] = 'Vrienden selecteren';
$l['select_buddies_desc'] = 'Om een of meerdere van uw vrienden als ontvangers te kiezen, moet u ze selecteren en hieronder op OK klikken.';
$l['selected_recipients'] = 'Geselecteerde ontvangers';
$l['ok'] = 'OK';
$l['cancel'] = 'Annuleren';
$l['online'] = 'Online';
$l['offline'] = 'Offline';
$l['edited_post'] = 'Bericht bewerkt';
$l['usergroup'] = 'Gebruikersgroep';
